In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.6/dist-packages (4.4.1)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly) (1.3.3)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from plotly) (1.15.0)

In [ ]:
!pip install folium

Requirement already satisfied: folium in /usr/local/lib/python3.6/dist-packages (0.8.3)
Requirement already satisfied: branca>=0.3.0 in /usr/local/lib/python3.6/dist-packages (from folium) (0.4.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from folium) (2.23.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/dist-packages (from folium) (2.11.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from folium) (1.18.5)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from folium) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->folium) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->folium) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->folium) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->folium) (2020.6.20)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2->folium) (1.1.1)

In [2]:
import pandas as pd
import numpy as np
import json
import folium
import plotly.offline as pyo
import plotly.graph_objs as go

In [121]:
# 서울시 구별 인구
ppl = pd.read_csv("/content/drive/My Drive/project/seoul_contest/서울시 주민등록인구 (연령별동별) 통계.txt",header=None , sep='\t')
ppl.loc[0]
ppl.columns
ppl = ppl.loc[:,[1,  2,  3,  4,  ]]
ppl.columns = ppl.loc[0]
ppl = ppl.loc[1:].set_index('자치구')
pop = ppl[ppl['구분']=='계']
pop = pop[pop['동']=='소계']
pop_by_gu=pd.DataFrame(pop['계'])
# pop_by_gu.to_pickle('population.pkl')

In [128]:
# 서울시 동별 인구
ppl = pd.read_csv("/content/drive/My Drive/project/seoul_contest/서울시 주민등록인구 (연령별동별) 통계.txt",header=None , sep='\t')
ppl.loc[0]
ppl.columns
ppl = ppl.loc[:,[1,  2,  3,  4,  ]]
ppl.columns = ppl.loc[0]
ppl = ppl.loc[1:].set_index('동')
pop = ppl[ppl['구분']=='계']
pop_by_dong = pop.loc[:,['자치구', '계']]
# pop_by_dong.to_pickle('population_by_dong.pkl')

In [297]:
a = pd.read_pickle('/content/drive/My Drive/project/seoul_contest/1인당 주차면적.pkl')
b = pd.read_pickle('/content/drive/My Drive/project/seoul_contest/crime_per_pop.pkl')
c = pd.read_pickle('/content/drive/My Drive/project/seoul_contest/crime_top5.pkl')
d = pd.read_pickle('/content/drive/My Drive/project/seoul_contest/population.pkl')
e = pd.read_pickle('/content/drive/My Drive/project/seoul_contest/population_by_dong.pkl')

#### test

In [268]:
e

0     자치구          계
동
합계     합계  9,985,652
소계    종로구    160,520
사직동   종로구      9,787
삼청동   종로구      2,973
부암동   종로구     10,421
...   ...        ...
둔촌1동  강동구        274
둔촌2동  강동구     27,292
암사1동  강동구     36,254
천호2동  강동구     35,642
길동    강동구     46,950

[451 rows x 2 columns]

In [298]:
e = e.reset_index()
ee= e[e['동']!='소계']
eee=ee[ee['동']!='합계']
eee[eee['동']=='신사동']
eee['구+동']=eee['자치구']+eee['동']
eee.sort_values('구+동',inplace=True)
eee.reset_index(inplace=True)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [284]:
# eee['구+동']=eee['자치구']+eee['동']
eee

0    level_0  index     동  자치구       계      구+동
393      393    393  개포1동  강남구   6,853  강남구개포1동
403      403    403  개포2동  강남구  22,540  강남구개포2동
394      394    394  개포4동  강남구  18,216  강남구개포4동
383      383    383  논현1동  강남구  23,916  강남구논현1동
384      384    384  논현2동  강남구  21,851  강남구논현2동
..       ...    ...   ...  ...     ...      ...
107      107    107  상봉2동  중랑구  20,036  중랑구상봉2동
113      113    113  신내1동  중랑구  40,611  중랑구신내1동
114      114    114  신내2동  중랑구  21,616  중랑구신내2동
108      108    108  중화1동  중랑구  20,699  중랑구중화1동
109      109    109  중화2동  중랑구  26,666  중랑구중화2동

[425 rows x 6 columns]

In [246]:
eee[eee['동']=='신사동']

0    index    동  자치구       계     구+동
244    351  신사동  관악구  25,976  관악구신사동
245    382  신사동  강남구  17,270  강남구신사동

In [285]:
st = pd.read_excel('/content/drive/My Drive/project/seoul_contest/서울시_행정동_법정동_20200814.xlsx')
s = st[st['시도명']=='서울특별시']
df=s[['행정동코드','시군구명','읍면동명']].dropna()
df = df.drop_duplicates(subset=['행정동코드'])
df['구+동']=df['시군구명']+df['읍면동명']
df.sort_values('구+동',inplace=True)
# df.reset_index(inplace=True)

In [292]:
df.reset_index(inplace=True)

In [293]:
df

     index       행정동코드 시군구명   읍면동명       구+동
0      702  1168066000  강남구   개포1동   강남구개포1동
1      703  1168067000  강남구   개포2동   강남구개포2동
2      705  1168069000  강남구   개포4동   강남구개포4동
3      688  1168052100  강남구   논현1동   강남구논현1동
4      689  1168053100  강남구   논현2동   강남구논현2동
..     ...         ...  ...    ...       ...
420    291  1126059000  중랑구  상봉제2동  중랑구상봉제2동
421    298  1126068000  중랑구   신내1동   중랑구신내1동
422    299  1126069000  중랑구   신내2동   중랑구신내2동
423    292  1126060000  중랑구  중화제1동  중랑구중화제1동
424    293  1126061000  중랑구  중화제2동  중랑구중화제2동

[425 rows x 5 columns]

In [299]:
eee

0    index     동  자치구       계      구+동
0      393  개포1동  강남구   6,853  강남구개포1동
1      403  개포2동  강남구  22,540  강남구개포2동
2      394  개포4동  강남구  18,216  강남구개포4동
3      383  논현1동  강남구  23,916  강남구논현1동
4      384  논현2동  강남구  21,851  강남구논현2동
..     ...   ...  ...     ...      ...
420    107  상봉2동  중랑구  20,036  중랑구상봉2동
421    113  신내1동  중랑구  40,611  중랑구신내1동
422    114  신내2동  중랑구  21,616  중랑구신내2동
423    108  중화1동  중랑구  20,699  중랑구중화1동
424    109  중화2동  중랑구  26,666  중랑구중화2동

[425 rows x 5 columns]

In [ ]:
len(total),len(eee)

(425, 425)

In [302]:
total= pd.concat([df,eee],axis=1,ignore_index=True)
total.columns=['0','행정동코드','시군구명','행정동명','4','5','행정동','구명','인구(동)','9']
total

       0       행정동코드 시군구명   행정동명         4    5   행정동   구명   인구(동)        9
0    702  1168066000  강남구   개포1동   강남구개포1동  393  개포1동  강남구   6,853  강남구개포1동
1    703  1168067000  강남구   개포2동   강남구개포2동  403  개포2동  강남구  22,540  강남구개포2동
2    705  1168069000  강남구   개포4동   강남구개포4동  394  개포4동  강남구  18,216  강남구개포4동
3    688  1168052100  강남구   논현1동   강남구논현1동  383  논현1동  강남구  23,916  강남구논현1동
4    689  1168053100  강남구   논현2동   강남구논현2동  384  논현2동  강남구  21,851  강남구논현2동
..   ...         ...  ...    ...       ...  ...   ...  ...     ...      ...
420  291  1126059000  중랑구  상봉제2동  중랑구상봉제2동  107  상봉2동  중랑구  20,036  중랑구상봉2동
421  298  1126068000  중랑구   신내1동   중랑구신내1동  113  신내1동  중랑구  40,611  중랑구신내1동
422  299  1126069000  중랑구   신내2동   중랑구신내2동  114  신내2동  중랑구  21,616  중랑구신내2동
423  292  1126060000  중랑구  중화제1동  중랑구중화제1동  108  중화1동  중랑구  20,699  중랑구중화1동
424  293  1126061000  중랑구  중화제2동  중랑구중화제2동  109  중화2동  중랑구  26,666  중랑구중화2동

[425 rows x 10 columns]

In [237]:
total['bool'] = total['시군구명'] == total['구명']
[total['bool']=='True']

/usr/local/lib/python3.6/dist-packages/pandas/core/computation/expressions.py:68: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

[0      False
 1      False
 2      False
 3      False
 4      False
        ...
 420    False
 421    False
 422    False
 423    False
 424    False
 Name: bool, Length: 425, dtype: bool]

In [406]:
total[total['행정동']=='여의동']

       0       행정동코드  시군구명 행정동명        4    5  행정동    구명   인구(동)        9
342  586  1156054000  영등포구  여의동  영등포구여의동  306  여의동  영등포구  34,675  영등포구여의동

In [162]:
dff = dff.reset_index()
dff[dff['index']=='신사동']

    index       행정동코드 시군구명  자치구       계
137   신사동  1162068500  관악구  관악구  25,976
138   신사동  1162068500  관악구  강남구  17,270
139   신사동  1168051000  강남구  관악구  25,976
140   신사동  1168051000  강남구  강남구  17,270

In [208]:
d

            계
자치구
종로구   160,520
중구    136,030
용산구   245,362
성동구   304,851
광진구   363,925
동대문구  360,380
중랑구   399,415
성북구   452,290
강북구   315,395
도봉구   331,744
노원구   533,041
은평구   483,938
서대문구  324,224
마포구   384,957
양천구   462,034
강서구   593,203
구로구   436,707
금천구   250,554
영등포구  405,154
동작구   406,776
관악구   516,318
서초구   433,062
강남구   546,158
송파구   678,067
강동구   461,547

In [356]:
all_ = pd.merge(total.set_index('구명'),d,left_index=True,right_index=True)
# all_.columns = ['1','행정동코드','행정동명','2','행정동','구명','인구(동)','bool','인구(구)']
all_=all_.astype('str')

In [352]:
all_[all_['행정동']=='신사동'] # 14/56 떨궈야댐
all_=all_['행정동코드'].astype('str')

In [368]:
aa = all_[['행정동코드', '시군구명', '행정동명','행정동', '인구(동)', '9', '계']]
aa['인구(동)']= aa['인구(동)'].str.replace(',', '').astype('int64')
aa['계']= aa['계'].str.replace(',', '').astype('int64')
aa['동비율']= aa['인구(동)']/ aa['계']
aa

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

          행정동코드 시군구명   행정동명   행정동  인구(동)        9       계       동비율
강남구  1168066000  강남구   개포1동  개포1동   6853  강남구개포1동  546158  0.012548
강남구  1168067000  강남구   개포2동  개포2동  22540  강남구개포2동  546158  0.041270
강남구  1168069000  강남구   개포4동  개포4동  18216  강남구개포4동  546158  0.033353
강남구  1168052100  강남구   논현1동  논현1동  23916  강남구논현1동  546158  0.043790
강남구  1168053100  강남구   논현2동  논현2동  21851  강남구논현2동  546158  0.040009
..          ...  ...    ...   ...    ...      ...     ...       ...
중랑구  1126059000  중랑구  상봉제2동  상봉2동  20036  중랑구상봉2동  399415  0.050163
중랑구  1126068000  중랑구   신내1동  신내1동  40611  중랑구신내1동  399415  0.101676
중랑구  1126069000  중랑구   신내2동  신내2동  21616  중랑구신내2동  399415  0.054119
중랑구  1126060000  중랑구  중화제1동  중화1동  20699  중랑구중화1동  399415  0.051823
중랑구  1126061000  중랑구  중화제2동  중화2동  26666  중랑구중화2동  399415  0.066763

[425 rows x 8 columns]

In [376]:
b = b[['합계(발생)', '합계(검거)','검거율', '계']]
b

      합계(발생)  합계(검거)         검거율       계
종로구     3846    4117  107.046282  160520
중구      4327    2804   64.802404  136030
용산구     3313    2611   78.810746  245362
성동구     2512    1838   73.168790  304851
광진구     4011    2816   70.206931  363925
동대문구    3692    2818   76.327194  360380
중랑구     4268    3138   73.523899  399415
성북구     2877    2323   80.743830  452290
강북구     3838    3023   78.764982  315395
도봉구     2110    1497   70.947867  331744
노원구     4153    2964   71.370094  533041
은평구     3880    3000   77.319588  483938
서대문구    2943    2020   68.637445  324224
마포구     4842    3170   65.468815  384957
양천구     3214    2124   66.085874  462034
강서구     4924    3543   71.953696  593203
구로구     4707    3291   69.917145  436707
금천구     3105    2343   75.458937  250554
영등포구    5820    3787   65.068729  405154
동작구     3400    2195   64.558824  406776
관악구     5328    3810   71.509009  516318
서초구     5542    3750   67.665103  433062
강남구     7304    5069   69.400329  546158
송파구     5698    3799   66.672517  678067
강동구     4014    2955   73.617339  461547

In [390]:
whole = pd.merge(aa,b,left_index=True,right_index=True)
whole['동(발생)'] = whole['동비율']*whole['합계(발생)']
whole['동(검거)'] = whole['동비율']*whole['합계(검거)']
whole['동(검거율)']=whole['합계(검거)']/whole['합계(발생)']
whole['인구대비범죄율']=whole['동(발생)']/whole['인구(동)']
whole.reset_index(inplace=True)
whole.columns
whole = whole[['행정동코드', '시군구명', '행정동명', '행정동', '인구(동)', '9', '계_x', '동비율', '합계(발생)','합계(검거)', '검거율', '동(발생)', '동(검거)', '동(검거율)', '인구대비범죄율']]
whole
# whole[['행정동코드', '시군구명', '행정동명', '행정동', '인구(동)', '구+동', '자치구인구', '동비율', '구별합계(발생)','구별합계(검거)', '검거율', '동(발생)', '동(검거)', '동(검거율)', '인구대비범죄율']]

          행정동코드 시군구명   행정동명   행정동  ...       동(발생)       동(검거)    동(검거율)   인구대비범죄율
0    1168066000  강남구   개포1동  개포1동  ...   91.648043   63.604043  0.694003  0.013373
1    1168067000  강남구   개포2동  개포2동  ...  301.436874  209.198181  0.694003  0.013373
2    1168069000  강남구   개포4동  개포4동  ...  243.610208  169.066285  0.694003  0.013373
3    1168052100  강남구   논현1동  논현1동  ...  319.838699  221.969108  0.694003  0.013373
4    1168053100  강남구   논현2동  논현2동  ...  292.222588  202.803436  0.694003  0.013373
..          ...  ...    ...   ...  ...         ...         ...       ...       ...
420  1126059000  중랑구  상봉제2동  상봉2동  ...  214.097237  157.412636  0.735239  0.010686
421  1126068000  중랑구   신내1동  신내1동  ...  433.954028  319.059920  0.735239  0.010686
422  1126069000  중랑구   신내2동  신내2동  ...  230.980529  169.825890  0.735239  0.010686
423  1126060000  중랑구  중화제1동  중화1동  ...  221.181808  162.621489  0.735239  0.010686
424  1126061000  중랑구  중화제2동  중화2동  ...  284.942949  209.501165  0.735239  0.010686

[425 rows x 15 columns]

In [360]:
# 신사동	관악구	25,976/516,318     1162068500	관악구
# 신사동	강남구	17,270/546,158     1168051000	강남구
# all.drop([14,56],inplace=True)

In [329]:
# all[all['행정동']=='항동']
# all[all['행정동']=='여의도동']
all[all['행정동']=='여의동'] # 14/56 떨군거 확인

    index  행정동       행정동코드   자치구   인구(동)    인구(구)
198  영등포구  여의동  1156054000  영등포구  34,675  405,154

In [347]:
# parking = parking.reset_index()
# parking = parking[parking['동']!='합계']
# parking =  parking[parking['동']!='소계']
parking['구+동']=parking['자치구']+parking['동']
parking.to_csv('인구랑 행정동코드.csv',encoding='cp949')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [323]:
parking

     level_0  index     동  자치구  ... 합계(공영면수) 합계(민영개수) 합계(민영면수)      구+동
0          0      2   사직동  종로구  ...    1,478      340   12,739   종로구사직동
1          1      3   삼청동  종로구  ...      153      154    1,700   종로구삼청동
2          2      4   부암동  종로구  ...      133      588    3,341   종로구부암동
3          3      5   평창동  종로구  ...      277    1,578    9,343   종로구평창동
4          4      6   무악동  종로구  ...        -       45    3,249   종로구무악동
..       ...    ...   ...  ...  ...      ...      ...      ...      ...
419      419    445  둔촌1동  강동구  ...        -       21      388  강동구둔촌1동
420      420    446  둔촌2동  강동구  ...      528    1,115   16,116  강동구둔촌2동
421      421    447  암사1동  강동구  ...      455    2,305   16,802  강동구암사1동
422      422    448  천호2동  강동구  ...    2,739    2,793   16,604  강동구천호2동
423      423    449    길동  강동구  ...      937    2,031   23,885    강동구길동

[424 rows x 11 columns]

In [348]:
# parking[parking['동']=='여의도동']
# parking[parking['동']=='항동']
# parking=parking['ehd']
parking=parking[['동', '자치구', '합계(개소)', '합계(면수)','구+동']]
parking

        동  자치구 합계(개소)  합계(면수)      구+동
0     사직동  종로구    360  14,217   종로구사직동
1     삼청동  종로구    169   1,853   종로구삼청동
2     부암동  종로구    596   3,474   종로구부암동
3     평창동  종로구  1,600   9,620   종로구평창동
4     무악동  종로구     45   3,249   종로구무악동
..    ...  ...    ...     ...      ...
419  둔촌1동  강동구     21     388  강동구둔촌1동
420  둔촌2동  강동구  1,116  16,644  강동구둔촌2동
421  암사1동  강동구  2,306  17,257  강동구암사1동
422  천호2동  강동구  2,799  19,343  강동구천호2동
423    길동  강동구  2,032  24,822    강동구길동

[424 rows x 5 columns]

pandas.core.series.Series

In [358]:
w = pd.merge(all_.set_index('9'),parking.set_index('구+동'),how='outer',left_index=True,right_index=True)
# w.columns = ['0', '행정동코드', '시군구명', '행정동명', '4', '5', '행정동', '인구(동)', '계', 'level','num', '동', '자치구', '합계(개소)', '합계(면수)', '합계(공영개수)', '합계(공영면수)','합계(민영개수)', '합계(민영면수)']
w

           0       행정동코드 시군구명   행정동명  ...     동  자치구 합계(개소)  합계(면수)
강남구개포1동  702  1168066000  강남구   개포1동  ...  개포1동  강남구     53   5,785
강남구개포2동  703  1168067000  강남구   개포2동  ...  개포2동  강남구    114   4,585
강남구개포4동  705  1168069000  강남구   개포4동  ...  개포4동  강남구    987   9,200
강남구논현1동  688  1168052100  강남구   논현1동  ...  논현1동  강남구  2,043  21,176
강남구논현2동  689  1168053100  강남구   논현2동  ...  논현2동  강남구  2,069  24,721
...      ...         ...  ...    ...  ...   ...  ...    ...     ...
중랑구상봉2동  291  1126059000  중랑구  상봉제2동  ...  상봉2동  중랑구    906   9,315
중랑구신내1동  298  1126068000  중랑구   신내1동  ...  신내1동  중랑구    494  15,803
중랑구신내2동  299  1126069000  중랑구   신내2동  ...  신내2동  중랑구    136   8,342
중랑구중화1동  292  1126060000  중랑구  중화제1동  ...  중화1동  중랑구    667   4,752
중랑구중화2동  293  1126061000  중랑구  중화제2동  ...  중화2동  중랑구    905   7,508

[426 rows x 13 columns]

In [391]:
w = w[['행정동코드', '시군구명', '행정동명', '행정동', '인구(동)', '계','동','합계(개소)', '합계(면수)']]
w.reset_index(inplace=True)

In [392]:
w

       index       행정동코드 시군구명   행정동명  ...        계     동 합계(개소)  합계(면수)
0    강남구개포1동  1168066000  강남구   개포1동  ...  546,158  개포1동     53   5,785
1    강남구개포2동  1168067000  강남구   개포2동  ...  546,158  개포2동    114   4,585
2    강남구개포4동  1168069000  강남구   개포4동  ...  546,158  개포4동    987   9,200
3    강남구논현1동  1168052100  강남구   논현1동  ...  546,158  논현1동  2,043  21,176
4    강남구논현2동  1168053100  강남구   논현2동  ...  546,158  논현2동  2,069  24,721
..       ...         ...  ...    ...  ...      ...   ...    ...     ...
421  중랑구상봉2동  1126059000  중랑구  상봉제2동  ...  399,415  상봉2동    906   9,315
422  중랑구신내1동  1126068000  중랑구   신내1동  ...  399,415  신내1동    494  15,803
423  중랑구신내2동  1126069000  중랑구   신내2동  ...  399,415  신내2동    136   8,342
424  중랑구중화1동  1126060000  중랑구  중화제1동  ...  399,415  중화1동    667   4,752
425  중랑구중화2동  1126061000  중랑구  중화제2동  ...  399,415  중화2동    905   7,508

[426 rows x 10 columns]

In [393]:
whole

          행정동코드 시군구명   행정동명   행정동  ...       동(발생)       동(검거)    동(검거율)   인구대비범죄율
0    1168066000  강남구   개포1동  개포1동  ...   91.648043   63.604043  0.694003  0.013373
1    1168067000  강남구   개포2동  개포2동  ...  301.436874  209.198181  0.694003  0.013373
2    1168069000  강남구   개포4동  개포4동  ...  243.610208  169.066285  0.694003  0.013373
3    1168052100  강남구   논현1동  논현1동  ...  319.838699  221.969108  0.694003  0.013373
4    1168053100  강남구   논현2동  논현2동  ...  292.222588  202.803436  0.694003  0.013373
..          ...  ...    ...   ...  ...         ...         ...       ...       ...
420  1126059000  중랑구  상봉제2동  상봉2동  ...  214.097237  157.412636  0.735239  0.010686
421  1126068000  중랑구   신내1동  신내1동  ...  433.954028  319.059920  0.735239  0.010686
422  1126069000  중랑구   신내2동  신내2동  ...  230.980529  169.825890  0.735239  0.010686
423  1126060000  중랑구  중화제1동  중화1동  ...  221.181808  162.621489  0.735239  0.010686
424  1126061000  중랑구  중화제2동  중화2동  ...  284.942949  209.501165  0.735239  0.010686

[425 rows x 15 columns]

In [402]:
all_m = pd.merge(w.set_index('행정동코드'),whole.set_index('행정동코드'),how='outer',left_index=True,right_index=True)
all_m = all_m[['index', '시군구명_x', '행정동명_x', '행정동_x', '인구(동)_x', '계', '합계(개소)','합계(면수)','동비율','합계(발생)', '합계(검거)', '검거율', '동(발생)', '동(검거)', '동(검거율)', '인구대비범죄율']]
all_m.reset_index(inplace=True)

In [403]:
all_m

          행정동코드     index 시군구명_x  ...       동(검거)    동(검거율)   인구대비범죄율
0           NaN  영등포구여의도동    NaN  ...         NaN       NaN       NaN
1    1111051500  종로구청운효자동    종로구  ...  329.703682  1.070463  0.023960
2    1111053000    종로구사직동    종로구  ...  251.015942  1.070463  0.023960
3    1111054000    종로구삼청동    종로구  ...   76.251190  1.070463  0.023960
4    1111055000    종로구부암동    종로구  ...  267.276707  1.070463  0.023960
..          ...       ...    ...  ...         ...       ...       ...
421  1174065000   강동구성내2동    강동구  ...  160.674168  0.736173  0.008697
422  1174066000   강동구성내3동    강동구  ...  152.530338  0.736173  0.008697
423  1174068500     강동구길동    강동구  ...  300.591814  0.736173  0.008697
424  1174069000   강동구둔촌1동    강동구  ...    1.754253  0.736173  0.008697
425  1174070000   강동구둔촌2동    강동구  ...  174.733797  0.736173  0.008697

[426 rows x 17 columns]

In [412]:
all_m.columns = ['행정동코드', '구+동', '시군구명', '행정동명', '행정동', '인구(동)', '계','합계(개소)', '합계(면수)', '동비율', '합계(발생)', '합계(검거)', '검거율', '동(발생)', '동(검거)','동(검거율)', '인구대비범죄율']
all_m = all_m[1:]
all_m.to_pickle('/content/drive/My Drive/project/seoul_contest/Seoul_범죄율&주차구역.pkl')


#### 서울시 5대 범죄율 (구별) 2019년

In [ ]:
# crime = pd.read_csv("/content/drive/My Drive/project/seoul_contest/report서울시 5대 범죄 발생현황 통계(구별).txt",names=['5대범죄',	'5대범죄현황',	'합계'	,'종로구',	'중구',	'용산구'	,'성동구',	'광진구',	'동대문구',	'중랑구',	'성북구',	'강북구',	'도봉구',	'노원구',	'은평구',	'서대문구',	'마포구',	'양천구',	'강서구',	'구로구',	'금천구',	'영등포구',	'동작구'	,'관악구',	'서초구',	'강남구',	'송파구',	'강동구'])
crime = pd.read_csv("/content/drive/My Drive/project/seoul_contest/report서울시 5대 범죄 발생현황 통계(구별).txt",header=None , sep='\t', thousands = ',')
crime = crime[1:]
c = crime.T
crime_df = c[2:]
col=['5대범죄','합계(발생)'  ,'합계(검거)' , '살인(발생)' , '살인(검거)',  '강도(발생)' , '강도(검거)' , '강간강제추행(발생)' , '강간강제추행(검거)' , '절도(발생)' , '절도(검거)' , '폭력(발생)', '폭력(검거)']
crime_df.columns = col

In [ ]:
crime_df['합계(검거)'] = crime_df['합계(검거)'].str.replace(',', '').astype('int64')
crime_df['합계(발생)']= crime_df['합계(발생)'].str.replace(',', '').astype('int64')
crime_df['검거율'] = (crime_df['합계(검거)']/crime_df['합계(발생)'])*100
crime_df = crime_df.set_index('5대범죄')
# crime_df.to_pickle('crime_top5.pkl')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df = pd.merge(crime_df,pop_by_gu,left_index=True, right_index=True)
df['계'] = df['계'].str.replace(',', '').astype('int64')
df["인구대비 범죄 발생률"] = df['합계(발생)']/df['계']
df
# df.to_pickle('crime_per_pop.pkl')

      합계(발생)  합계(검거) 살인(발생) 살인(검거)  ... 폭력(검거)         검거율       계 인구대비 범죄 발생률
종로구     3846    4117      4      5  ...  1,892  107.046282  160520    0.023960
중구      4327    2804      2      1  ...  1,633   64.802404  136030    0.031809
용산구     3313    2611      3      3  ...  1,823   78.810746  245362    0.013502
성동구     2512    1838      6      5  ...  1,216   73.168790  304851    0.008240
광진구     4011    2816      4      5  ...  1,585   70.206931  363925    0.011022
동대문구    3692    2818      6      6  ...  1,833   76.327194  360380    0.010245
중랑구     4268    3138     10     10  ...  2,107   73.523899  399415    0.010686
성북구     2877    2323      3      3  ...  1,456   80.743830  452290    0.006361
강북구     3838    3023      6      6  ...  2,206   78.764982  315395    0.012169
도봉구     2110    1497      1      1  ...  1,014   70.947867  331744    0.006360
노원구     4153    2964      4      4  ...  2,118   71.370094  533041    0.007791
은평구     3880    3000      3      3  ...  1,857   77.319588  483938    0.008018
서대문구    2943    2020      2      1  ...  1,260   68.637445  324224    0.009077
마포구     4842    3170      2      2  ...  1,832   65.468815  384957    0.012578
양천구     3214    2124      6      6  ...  1,370   66.085874  462034    0.006956
강서구     4924    3543      8      9  ...  2,196   71.953696  593203    0.008301
구로구     4707    3291     10      9  ...  2,148   69.917145  436707    0.010778
금천구     3105    2343      6      6  ...  1,590   75.458937  250554    0.012393
영등포구    5820    3787     10     10  ...  2,467   65.068729  405154    0.014365
동작구     3400    2195      4      2  ...  1,503   64.558824  406776    0.008358
관악구     5328    3810     13     10  ...  2,369   71.509009  516318    0.010319
서초구     5542    3750      5      5  ...  2,210   67.665103  433062    0.012797
강남구     7304    5069      5      3  ...  3,159   69.400329  546158    0.013373
송파구     5698    3799      7      8  ...  2,535   66.672517  678067    0.008403
강동구     4014    2955      6      5  ...  1,874   73.617339  461547    0.008697

[25 rows x 15 columns]

In [ ]:
# 인구대비 범죄 발생률 top5
df.sort_values(by='인구대비 범죄 발생률', ascending=False).head(5)

      합계(발생)  합계(검거) 살인(발생) 살인(검거)  ... 폭력(검거)         검거율       계 인구대비 범죄 발생률
중구      4327    2804      2      1  ...  1,633   64.802404  136030    0.031809
종로구     3846    4117      4      5  ...  1,892  107.046282  160520    0.023960
영등포구    5820    3787     10     10  ...  2,467   65.068729  405154    0.014365
용산구     3313    2611      3      3  ...  1,823   78.810746  245362    0.013502
강남구     7304    5069      5      3  ...  3,159   69.400329  546158    0.013373

[5 rows x 15 columns]

In [ ]:
# 단순 범죄 발생 건수
df.sort_values(by='합계(발생)', ascending=False).head(5)

      합계(발생)  합계(검거) 살인(발생) 살인(검거)  ... 폭력(검거)        검거율       계 인구대비 범죄 발생률
강남구     7304    5069      5      3  ...  3,159  69.400329  546158    0.013373
영등포구    5820    3787     10     10  ...  2,467  65.068729  405154    0.014365
송파구     5698    3799      7      8  ...  2,535  66.672517  678067    0.008403
서초구     5542    3750      5      5  ...  2,210  67.665103  433062    0.012797
관악구     5328    3810     13     10  ...  2,369  71.509009  516318    0.010319

[5 rows x 15 columns]

In [ ]:
trace1 = go.Bar(x=crime_df['5대범죄'][1:], y=crime_df['합계(발생)'][1:])
data = [trace1]
layout = go.Layout(title='구별 범죄')
fig = go.Figure(data=data, layout=layout)
pyo.iplot(fig)

In [ ]:
trace2 = go.Bar(x=crime_df['5대범죄'][1:], y=crime_df['검거율'][1:])
data = [trace]
layout = go.Layout(title='구별 범죄 검거율')
fig = go.Figure(data=data, layout=layout)
pyo.iplot(fig)

In [ ]:
trace3 = go.Bar(x=df.index, y=df["인구대비 범죄 발생률"])
data = [trace3]
layout = go.Layout(title='구별 인구대비 범죄 발생률')
fig = go.Figure(data=data, layout=layout)
pyo.iplot(fig)

#### 서울시 주차장 통계

In [92]:
#  공영주차장 합계= 노상주차장 + 노외주차장 (시영,구영), 민영주차장 합계= 노외주차장 (민영) + 건축물부설
parking = pd.read_csv("/content/drive/My Drive/project/seoul_contest/서울시 주차장 (동별) 통계.txt" ,header=None, sep='\t')
parking = parking.loc[:,[1,2,3,4,5,6,7,8]]#.set_index(parking.loc[:,2])
col1 = ['자치구','동','합계(개소)','합계(면수)','합계(공영개수)','합계(공영면수)','합계(민영개수)','합계(민영면수)']
parking.columns = col1
# parking = parking.set_index('동')[3:]
# parking.to_pickle('parkinglot_sum.pkl')

In [116]:
parking = parking.reset_index()
parking = parking[parking['동']!='합계']
parking =  parking[parking['동']!='소계']
parking

        동  자치구 합계(개소)  합계(면수) 합계(공영개수) 합계(공영면수) 합계(민영개수) 합계(민영면수)
2     사직동  종로구    360  14,217       20    1,478      340   12,739
3     삼청동  종로구    169   1,853       15      153      154    1,700
4     부암동  종로구    596   3,474        8      133      588    3,341
5     평창동  종로구  1,600   9,620       22      277    1,578    9,343
6     무악동  종로구     45   3,249        -        -       45    3,249
..    ...  ...    ...     ...      ...      ...      ...      ...
445  둔촌1동  강동구     21     388        -        -       21      388
446  둔촌2동  강동구  1,116  16,644        1      528    1,115   16,116
447  암사1동  강동구  2,306  17,257        1      455    2,305   16,802
448  천호2동  강동구  2,799  19,343        6    2,739    2,793   16,604
449    길동  강동구  2,032  24,822        1      937    2,031   23,885

[424 rows x 8 columns]

In [109]:
# parking_dong = parking.drop("소계", axis=0)
pop_by_dong = pop_by_dong.drop("소계", axis=0)

In [118]:
parking_dong

      자치구   합계(개소)     합계(면수) 합계(공영개수) 합계(공영면수) 합계(민영개수)   합계(민영면수)
동
합계     합계  314,392  4,250,682   11,083  187,446  303,309  4,063,236
사직동   종로구      360     14,217       20    1,478      340     12,739
삼청동   종로구      169      1,853       15      153      154      1,700
부암동   종로구      596      3,474        8      133      588      3,341
평창동   종로구    1,600      9,620       22      277    1,578      9,343
...   ...      ...        ...      ...      ...      ...        ...
둔촌1동  강동구       21        388        -        -       21        388
둔촌2동  강동구    1,116     16,644        1      528    1,115     16,116
암사1동  강동구    2,306     17,257        1      455    2,305     16,802
천호2동  강동구    2,799     19,343        6    2,739    2,793     16,604
길동    강동구    2,032     24,822        1      937    2,031     23,885

[425 rows x 7 columns]

In [136]:
pop_by_gu

            계
자치구
종로구   160,520
중구    136,030
용산구   245,362
성동구   304,851
광진구   363,925
동대문구  360,380
중랑구   399,415
성북구   452,290
강북구   315,395
도봉구   331,744
노원구   533,041
은평구   483,938
서대문구  324,224
마포구   384,957
양천구   462,034
강서구   593,203
구로구   436,707
금천구   250,554
영등포구  405,154
동작구   406,776
관악구   516,318
서초구   433,062
강남구   546,158
송파구   678,067
강동구   461,547

In [132]:
# pop_by_dong = pop_by_dong.reset_index()
# pop_by_dong
pop_by_dong = pop_by_dong[pop_by_dong['동']!='합계']
pop_by_dong = pop_by_dong[pop_by_dong['동']!='소계']

# pop_by_dong[pop_by_dong['동']=='신사동']
pop_by_dong

0       동  자치구       계
2     사직동  종로구   9,787
3     삼청동  종로구   2,973
4     부암동  종로구  10,421
5     평창동  종로구  18,696
6     무악동  종로구   8,691
..    ...  ...     ...
446  둔촌1동  강동구     274
447  둔촌2동  강동구  27,292
448  암사1동  강동구  36,254
449  천호2동  강동구  35,642
450    길동  강동구  46,950

[425 rows x 3 columns]

In [ ]:
# 구 단위 주차면적
parking_gu= parking.loc["소계"].set_index('자치구')
lot_gu = pd.merge(pop_by_gu,parking_gu,left_index = True,right_index=True)
lot_gu['합계(면수)'] = lot_gu['합계(면수)'].str.replace(',', '').astype('int64')
lot_gu['계']= lot_gu['계'].str.replace(',', '').astype('int64')
lot_gu['1인당 주차면적'] = lot_gu['합계(면수)']/lot_gu['계']
lot_gu

           계  합계(개소)  합계(면수) 합계(공영개수) 합계(공영면수) 합계(민영개수) 합계(민영면수)  1인당 주차면적
자치구
종로구   160520   7,103   95350      194    6,142    6,909   89,208  0.594007
중구    136030   4,228  107399      178    5,408    4,050  101,991  0.789524
용산구   245362   7,390  113591      424    6,532    6,966  107,059  0.462953
성동구   304851   6,649  133724      287    8,174    6,362  125,550  0.438654
광진구   363925  17,495  138741    1,350    5,619   16,145  133,122  0.381235
동대문구  360380  10,455  138200      685    6,026    9,770  132,174  0.383484
중랑구   399415  12,381  133615      562   11,119   11,819  122,496  0.334527
성북구   452290  13,014  156915      219    7,283   12,795  149,632  0.346934
강북구   315395  10,969   91187       49    5,108   10,920   86,079  0.289120
도봉구   331744   9,660  109751      488    5,432    9,172  104,319  0.330830
노원구   533041   6,855  176629      187    3,986    6,668  172,643  0.331361
은평구   483938  18,790  146696      134    5,721   18,656  140,975  0.303130
서대문구  324224  11,382  112259      661    5,946   10,721  106,313  0.346239
마포구   384957  13,066  186203       48    7,139   13,018  179,064  0.483698
양천구   462034  11,694  162797      517    7,206   11,177  155,591  0.352349
강서구   593203  18,962  262157      673    8,545   18,289  253,612  0.441935
구로구   436707  10,632  183896      344    5,343   10,288  178,553  0.421097
금천구   250554   9,149  129455       68    4,018    9,081  125,437  0.516675
영등포구  405154  10,907  184322    2,183    9,559    8,724  174,763  0.454943
동작구   406776   8,306  134083      120    3,668    8,186  130,415  0.329624
관악구   516318  20,442  152131       65    7,516   20,377  144,615  0.294646
서초구   433062  12,390  261294      814    7,396   11,576  253,898  0.603364
강남구   546158  19,829  395951      103   13,856   19,726  382,095  0.724975
송파구   678067  22,650  351025      685   19,309   21,965  331,716  0.517685
강동구   461547  19,994  193311       45   11,395   19,949  181,916  0.418833

In [138]:
parking[parking['동']=='신사동']

       동  자치구 합계(개소)  합계(면수) 합계(공영개수) 합계(공영면수) 합계(민영개수) 합계(민영면수)
350  신사동  관악구  1,883   6,704        7      658    1,876    6,046
381  신사동  강남구  1,167  17,424        8    1,519    1,159   15,905

In [134]:
# 동 단위 주차면적
lot = pd.merge(pop_by_dong.set_index('동'),parking.set_index('동'),left_index = True,right_index=True)
lot['합계(면수)'] = lot['합계(면수)'].str.replace(',', '').astype('int64')
lot['계']= lot['계'].str.replace(',', '').astype('int64')
lot['1인당 주차면적'] = lot['합계(면수)']/lot['계']m
lot_df=lot.reset_index()
lot_df
# lot.to_pickle('1인당 주차면적.pkl')

        동 자치구_x      계 자치구_y  ... 합계(공영면수)  합계(민영개수) 합계(민영면수)  1인당 주차면적
0    가락1동   송파구  28065   송파구  ...    1,010        56   19,932  0.746196
1    가락2동   송파구  33503   송파구  ...    1,123     1,031   13,217  0.428021
2    가락본동   송파구  27715   송파구  ...      132     1,047   14,236  0.518420
3    가리봉동   구로구  15062   구로구  ...      289       353    2,211  0.165981
4     가산동   금천구  24830   금천구  ...      825       759   47,735  1.955699
..    ...   ...    ...   ...  ...      ...       ...      ...       ...
420   효창동   용산구  10387   용산구  ...      388       324    3,543  0.378454
421   후암동   용산구  18354   용산구  ...      249       720    4,351  0.250627
422  휘경1동  동대문구  15421  동대문구  ...      319       435    4,155  0.290124
423  휘경2동  동대문구  25132  동대문구  ...      280       807   10,828  0.441986
424   흑석동   동작구  34992   동작구  ...      101       273   16,947  0.487197

[425 rows x 11 columns]

In [146]:
lot_df[lot_df['동']=='신사동'] #245/246 drop해야함

       동 자치구_x      계 자치구_y  ... 합계(공영면수)  합계(민영개수) 합계(민영면수)  1인당 주차면적
244  신사동   관악구  25976   관악구  ...      658     1,876    6,046  0.258084
245  신사동   관악구  25976   강남구  ...    1,519     1,159   15,905  0.670773
246  신사동   강남구  17270   관악구  ...      658     1,876    6,046  0.388188
247  신사동   강남구  17270   강남구  ...    1,519     1,159   15,905  1.008917

[4 rows x 11 columns]

In [154]:
lot_df.drop(lot_df.loc[245:246].index,inplace=True)
# df.drop(df.index[:3], inplace=True)

In [155]:
# 떨궈진것 확인
lot_df[lot_df['동']=='신사동']

       동 자치구_x      계 자치구_y  ... 합계(공영면수)  합계(민영개수) 합계(민영면수)  1인당 주차면적
244  신사동   관악구  25976   관악구  ...      658     1,876    6,046  0.258084
247  신사동   강남구  17270   강남구  ...    1,519     1,159   15,905  1.008917

[2 rows x 11 columns]

In [ ]:
# 주차면적 높은 동 top10
lot.sort_values(by='1인당 주차면적', ascending=False).head(10)

            자치구_x      계 자치구_y 합계(개소)  ...  합계(공영면수) 합계(민영개수) 합계(민영면수)  1인당 주차면적
동                                      ...
소공동            중구   3045    중구    155  ...       112      148   13,861  4.588834
명동             중구   3693    중구    291  ...       141      280   14,329  3.918224
을지로동           중구   1993    중구    132  ...     1,201      122    3,513  2.365278
회현동            중구   5814    중구    191  ...       211      174   12,137  2.123839
종로1.2.3.4가동   종로구   8526   종로구    569  ...     1,687      550   16,414  2.123035
가산동           금천구  24830   금천구    775  ...       825      759   47,735  1.955699
삼성1동          강남구  14924   강남구    775  ...     1,644      767   24,338  1.740954
사직동           종로구   9787   종로구    360  ...     1,478      340   12,739  1.452641
역삼1동          강남구  36921   강남구  3,467  ...       996    3,457   52,418  1.446711
둔촌1동          강동구    274   강동구     21  ...         -       21      388  1.416058

[10 rows x 10 columns]

In [ ]:
trace4 = go.Bar(x=lot.index, y=lot["1인당 주차면적"])
data = [trace4]
layout = go.Layout(title='동별 1인당 주차면적(m^2)')
fig = go.Figure(data=data, layout=layout)
pyo.iplot(fig)

##### 지도 데이터 시각화(하는중)

In [ ]:
geo_data = 'data/seoul-dong.geojson'

ModuleNotFoundError: ignored

In [ ]:
lot.index[0]

'가락1동'

In [ ]:
# 먼저 인구를 구 단위로 묶습니다.
center = [37.541, 126.986] # 맵이 center 에 위치하고, zoom 레벨은 11로 시작하는 맵 m을 만듭니다. m = folium.Map(location=center, zoom_start=10) # Choropleth 레이어를 만들고, 맵 m에 추가합니다. folium.Choropleth( geo_data=geo_data, data=df, columns=('동', '인구'), key_on='feature.properties.동', fill_color='BuPu', legend_name='노령 인구수', ).add_to(m)

m = folium.Map(location=center, zoom_start=10)

folium.Choropleth( geo_data='data/seoul-dong.geojson', data=lot, columns=('자치구_x', '1인당 주차면적'),
                  key_on='feature.properties.구', fill_color='BuPu', legend_name='노령 인구수', ).add_to(m)

m

FileNotFoundError: ignored