# 공원데이터분석

In [1]:
# !pip install dbfread
# !pip install haversine
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from haversine import haversine
from tqdm.notebook import tqdm
%matplotlib inline
import platform
import pickle
import re
platform.system()
if platform.system() == 'Darwin': # Mac 환경 폰트 설정
    plt.rc('font', family='AppleGothic')
elif platform.system() == 'Windows': # Windows 환경 폰트 설정
    plt.rc('font', family='Malgun Gothic')
plt.rc('axes', unicode_minus=False) # 마이너스 폰트 설정
%config InlineBackend.figure_format = 'retina'

Requirement already satisfied: dbfread in c:\anaconda3\lib\site-packages (2.0.7)
Requirement already satisfied: haversine in c:\anaconda3\lib\site-packages (2.3.0)

In [4]:
bus = pd.read_excel(r'C:\Users\이규호\NLP\github\seoul_contest\data\서울시버스정류소좌표데이터(2020.03.06).xlsx', encoding='cp949')
park = pd.read_csv(r'C:\Users\이규호\NLP\github\seoul_contest\data\서울시 주요 공원현황.csv', encoding='cp949')
# lib = pd.read_excel(r'C:\Users\이규호\NLP\github\seoul_contest\data\전국도서관표준데이터-20200926.xls', encoding='cp949')
# sports = pd.read_csv()

In [8]:
park

,공원번호,공원명,공원개요,면적,개원일,주요시설,주요식물,안내도,오시는길,이용시참고사항,이미지,지역,공원주소,관리부서,전화번호,X좌표(GRS80TM),Y좌표(GRS80TM),X좌표(WGS84),Y좌표(WGS84),바로가기
0,1,남산도시자연공원,남산공원은 도심에 위치하여 서울시민에게 맑은 공기를 제공하는 자연휴식처이며 산책 꽃...,2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡,1968.9.10,기반시설 : 광장 45950㎡ 도로 108530㎡ 산책로 6.7㎞ (북측:3.7㎞/...,소나무 단풍 아카시아 상수리나무 등 191종 2881870주,http://parks.seoul.go.kr/upload/seditorMulti/2...,명동역(남산케이블카 와룡묘 서울애니메이션센터 방면) 도보 명동역 3번출구 → 퍼시픽...,남산공원 차량통행 금지안내 2005년 5월 1일부터 남산공원에 일반승용차 택시 통행...,http://parks.seoul.go.kr/file/info/view.do?fId...,중구,서울특별시 중구 삼일대로 231(예장동),서울특별시중부푸른도시사업소,02-3783-5900,198364.107000,4.503956e+05,126.990377,37.550140,http://parks.seoul.go.kr/template/sub/namsan.do
1,3,길동생태공원,길동생태공원은 생물의 서식처를 제공하고 종다양성을 증진시키며 자연생태계의 생물들을 ...,80683㎡,1999.5.20,탐방객안내소 야외전시대 관찰대 목재데크 조류관찰대 길동생태문화센터,소나무 보리수 등 64종 31800주 산국 부들 등 138종 192800본,http://parks.seoul.go.kr/template/common/img/p...,NaN,매주 월요일은 휴관입니다 사전예약 후 입장하실 수 있습니다. ▶ 인터넷 예약 바로가...,http://parks.seoul.go.kr/file/info/view.do?fId...,강동구,서울특별시 강동구 천호대로 1291(길동생태공원),동부공원녹지사업소 길동생태공원,02-489-2770,213554.120000,4.488527e+05,127.154779,37.540394,http://parks.seoul.go.kr/template/sub/gildong.do
2,4,서울대공원,서울대공원은 세계 각국의 야생동물들이 살아 숨 쉬는 서울동물원과 다양한 재미와 즐거...,9132690m²,1984.5.1,동물원 식물원 테마가든(장미원 어린이동물원 피크닉장) 치유숲 산림욕장 캠핑장 국립현...,NaN,NaN,지하철 4호선 대공원역 하차(2번 출구) 도보 15분 정도 문의처 02)500-73...,일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...,http://parks.seoul.go.kr/file/info/view.do?fId...,과천시,경기도 과천시 대공원광장로 102,전략기획실,02-500-7032,200994.267000,4.371640e+05,127.019847,37.426449,http://grandpark.seoul.go.kr/
3,5,서울숲,당초 골프장 승마장 등이 있던 뚝섬일대를 주거업무 지역으로 개발할 경우 약 4조원에...,480994㎡,2005.6.18,4개 테마공원: 문화예술공원 자연생태숲 자연체험학습원 습지생태원 주요시설: 가족마당...,수 목 : 소나무 섬잣나무 계수나무 외 95종 415795주 식물원 : 선인장 등 ...,http://parks.seoul.go.kr/template/common/img/p...,NaN,지하철 분당선 서울숲역 3번출구 도보로 약5분 2호선 뚝섬역 8번출구 도보로 약 1...,http://parks.seoul.go.kr/file/info/view.do?fId...,성동구,서울특별시 성동구 뚝섬로 273 (성수동1가),서울숲 관리사무소,02-460-2905,203695.432000,4.492907e+05,127.041798,37.543072,http://parks.seoul.go.kr/template/sub/seoulfor...
4,6,월드컵공원,월드컵공원은 서울의 서쪽에 위치하여 1978년부터 1993년까지 15년간 서울시민이...,2284085㎡,2002.5.1,평화의 공원 월드컵공원전시관(879㎡) 유니세프광장(2400㎡) 평화광장(5217㎡...,NaN,http://parks.seoul.go.kr/template/common/img/p...,지하철 6호선 월드컵경기장역 하차 → 1번 출구로 나온 후 직진 → 큰길(도로)이 ...,일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...,http://parks.seoul.go.kr/file/info/view.do?fId...,마포구,서울특별시 마포구 하늘공원로 84(월드컵공원),월드컵공원,02-300-5500,190658.070000,4.515988e+05,126.878907,37.571805,http://parks.seoul.go.kr/template/sub/worldcup...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,1378,용마도시자연공원(사가정공원),2005년 4월 13일 개장한 사가정공원은 면목동 산 50번지 일대의 면목약수터지구...,109635㎡,2005.4.13,피크닉장 놀이터 체력단련장 체육관,NaN,NaN,NaN,NaN,http://parks.seoul.go.kr/file/info/view.do?fId...,중랑구,서울특별시 중랑구 면목7동 산50,중랑구청 공원녹지과,02-2094-2993,NaN,NaN,127.095997,37.579762,NaN
128,1379,문화비축기지,매봉산자락에 위치한 문화비축기지는 폐산업시설인 '마포석유비축기지'를 재생하여 역사적...,140022㎡,2017.9.1,6개의탱크와 문화마당 녹지,NaN,http://parks.seoul.go.kr/upload/seditorMulti/2...,NaN,? 일반사항 - 공원은 연중무휴이나 전시관은 월요일 휴관입니다. - 공원을 ...,http://parks.seoul.go.kr/file/info/view.do?fId...,마포구,서울특별시 마포구 증산로 87,문화비축기지,02-376-8410,114264.460400,3.712093e+06,126.893245,37.571718,http://parks.seoul.go.kr/template/sub/culturet...
129,1380,경춘선숲길,일제 강점기때 우리 민족의 자본으로 만든 최초의 철도시설로 1939년 7월 25일 ...,211392㎡,NaN,조경시설 : 텃밭 잔디광장 철길 산책로 등 건축시설 : 무궁화호 객차(방문자센터) ...,NaN,NaN,지하철 이용시 지하철 7호선 하계역 4번출구 미성/장미아파트 도로 450m직진 지하...,○ 6.3km (시 작 점 : 육사삼거리 중간지점 : 화랑대사거리 → 화랑대...,http://parks.seoul.go.kr/file/info/view.do?fId...,NaN,노원구 공릉2동 산 82-2,중부공원녹지사업소,02-2289-4012,127.076482,3.762708e+01,127.076482,37.627077,NaN
130,1381,율현공원,? 율현공원은 보금자리주택 세곡2지구 사업의 결과물로 만들어졌다. 공원은 주택지구의...,157535㎡,2016.11.1,관리시설 : 사무실 조경시설 : 정자(4개) 조형쉼터(10개) 조형파고라(3개) 수...,수목 : 소나무 이팝나무 등 110종 143069주 초화 : 맥문동 벌개미취 등...,http://parks.seoul.go.kr/upload/seditorMulti/2...,NaN,공원 인근에 서울공항 활주로가 위치하고 있어 공원 내에서 드론을 날리거나 헬륨가스 ...,http://parks.seoul.go.kr/file/info/view.do?fId...,강남구,서울특별시 강남구 율현동 밤고개로24길(율현동 56),동부공원녹지사업소,02-459-9452,NaN,NaN,127.115594,37.472332,NaN
131,1382,서울로7017,서울로7017은 70년대 준공된 서울역 고가가 안전에 문제점이 도출되면서 철거가 될...,NaN,NaN,NaN,NaN,NaN,중림 만리동(서울로 종점부에서 진입) 지하철- 충정로(경기대입구) - 2 5호선 :...,NaN,http://parks.seoul.go.kr/file/info/view.do?fId...,중구,서울로7017,서울로운영단,02-313-7017,NaN,NaN,NaN,NaN,NaN

In [9]:
park.columns

Index(['공원번호', '공원명', '공원개요', '면적', '개원일', '주요시설', '주요식물', '안내도', '오시는길',
       '이용시참고사항', '이미지', '지역', '공원주소', '관리부서', '전화번호', 'X좌표(GRS80TM)',
       'Y좌표(GRS80TM)', 'X좌표(WGS84)', 'Y좌표(WGS84)', '바로가기'],
      dtype='object')

In [8]:
park_df = park[['공원번호','공원명','면적','개원일','주요시설','지역','공원주소','X좌표(WGS84)','Y좌표(WGS84)']]
park_df

,공원번호,공원명,면적,개원일,주요시설,지역,공원주소,X좌표(WGS84),Y좌표(WGS84)
0,1,남산도시자연공원,2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡,1968.9.10,기반시설 : 광장 45950㎡ 도로 108530㎡ 산책로 6.7㎞ (북측:3.7㎞/...,중구,서울특별시 중구 삼일대로 231(예장동),126.990377,37.550140
1,3,길동생태공원,80683㎡,1999.5.20,탐방객안내소 야외전시대 관찰대 목재데크 조류관찰대 길동생태문화센터,강동구,서울특별시 강동구 천호대로 1291(길동생태공원),127.154779,37.540394
2,4,서울대공원,9132690m²,1984.5.1,동물원 식물원 테마가든(장미원 어린이동물원 피크닉장) 치유숲 산림욕장 캠핑장 국립현...,과천시,경기도 과천시 대공원광장로 102,127.019847,37.426449
3,5,서울숲,480994㎡,2005.6.18,4개 테마공원: 문화예술공원 자연생태숲 자연체험학습원 습지생태원 주요시설: 가족마당...,성동구,서울특별시 성동구 뚝섬로 273 (성수동1가),127.041798,37.543072
4,6,월드컵공원,2284085㎡,2002.5.1,평화의 공원 월드컵공원전시관(879㎡) 유니세프광장(2400㎡) 평화광장(5217㎡...,마포구,서울특별시 마포구 하늘공원로 84(월드컵공원),126.878907,37.571805
...,...,...,...,...,...,...,...,...,...
127,1378,용마도시자연공원(사가정공원),109635㎡,2005.4.13,피크닉장 놀이터 체력단련장 체육관,중랑구,서울특별시 중랑구 면목7동 산50,127.095997,37.579762
128,1379,문화비축기지,140022㎡,2017.9.1,6개의탱크와 문화마당 녹지,마포구,서울특별시 마포구 증산로 87,126.893245,37.571718
129,1380,경춘선숲길,211392㎡,NaN,조경시설 : 텃밭 잔디광장 철길 산책로 등 건축시설 : 무궁화호 객차(방문자센터) ...,NaN,노원구 공릉2동 산 82-2,127.076482,37.627077
130,1381,율현공원,157535㎡,2016.11.1,관리시설 : 사무실 조경시설 : 정자(4개) 조형쉼터(10개) 조형파고라(3개) 수...,강남구,서울특별시 강남구 율현동 밤고개로24길(율현동 56),127.115594,37.472332
131,1382,서울로7017,NaN,NaN,NaN,중구,서울로7017,NaN,NaN

공원번호는 전국 기준인듯하고, 면적은 몇몇개는 re써서 뽑아야할듯. 개원일은 큰 의미있을지는 모르겠다.주요시설에선 valuecount랑 unique본다음에 특수점으로 넣을지 생각하고, 지역이 대부분있는듯하지만 없으면 주소에서 뽑아야할듯.

In [14]:
park_need = park_df[['공원명','X좌표(WGS84)','Y좌표(WGS84)', '면적']]
park_need.면적 = park_need.면적.astype(str)
park_need

C:\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

,공원명,X좌표(WGS84),Y좌표(WGS84),면적
0,남산도시자연공원,126.990377,37.550140,2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡
1,길동생태공원,127.154779,37.540394,80683㎡
2,서울대공원,127.019847,37.426449,9132690m²
3,서울숲,127.041798,37.543072,480994㎡
4,월드컵공원,126.878907,37.571805,2284085㎡
...,...,...,...,...
127,용마도시자연공원(사가정공원),127.095997,37.579762,109635㎡
128,문화비축기지,126.893245,37.571718,140022㎡
129,경춘선숲길,127.076482,37.627077,211392㎡
130,율현공원,127.115594,37.472332,157535㎡
131,서울로7017,NaN,NaN,nan

In [33]:
for i in range(len(park_need.면적)):
    print(re.findall('([1-9]+?\.?[1-9]+?)㎡', park_need.면적[i]))

['2896887', '442747']
['683']
[]
['994']
['85']
['8948.1']
['23.18', '255', '8.55', '83.36']
[]
[]
[]
['5197.7']
['11467']
['229539']
[]
[]
['61544', '792', '14152']
[]
['552']
[]
[]
[]
[]
['258991']
[]
[]
[]
['297926']
['411972']
[]
['38741.3']
['3715.2']
[]
[]
['29843.8']
['26']
['2.7']
['26']
[]
['31']
[]
['2277252']
[]
['138596']
[]
['254648']
['29816.5']
['762642']
[]
['99599.9']
[]
[]
[]
['9.6']
['72132']
['27.8']
['265582']
['4.9']
[]
['993724']
['219167', '8259']
['1349556.4']
['1511198']
['97565']
['18']
['1447122']
[]
['18689']
['954553']
['1667848']
['13224']
['345']
['5332422']
['7964']
['47832']
['213552']
['99.87']
['359435.2']
[]
['735']
[]
['359342.8']
['632733']
['18']
['6691885.3']
['285757']
[]
['29682.2']
['137759']
[]
[]
['662543']
['217946']
[]
['34955']
['83']
['4835']
[]
[]
['712']
['17182']
['349.3']
['87432.4']
['13467']
['46871']
['49972']
['74385']
['8868']
['634']
['22113']
[]
['82847']
['3692455']
[]
[]
['833']
['2752421']
['551']
['147859']
[]
[]
['519782']
['59347']
[]
[]
[]
['45615']
['21']
['9635']
['22']
['211392']
['157535']
[]

# 버스

In [5]:
bus

            표준ID  ARS-ID           정류장명         X좌표        Y좌표   비고
0      100000001    1001        종로2가사거리  126.987750  37.569765  NaN
1      100000002    1002    창경궁.서울대학교병원  126.996566  37.579183  NaN
2      100000003    1003      명륜3가.성대입구  126.998340  37.582671  NaN
3      100000004    1004       종로2가.삼일교  126.987613  37.568579  NaN
4      100000005    1005  혜화동로터리.여운형활동터  127.001744  37.586243  NaN
...          ...     ...            ...         ...        ...  ...
11275  124000334   25995          우성아파트  127.139339  37.550386  NaN
11276  124000333   25996          우성아파트  127.140046  37.550643  NaN
11277  124000332   25997           조일약국  127.123596  37.533630  NaN
11278  124000331   25998           성내시장  127.125497  37.536155  NaN
11279  124000330   25999    천호우체국.로데오거리  127.127337  37.540343  NaN

[11280 rows x 6 columns]

In [6]:
del bus['비고']

In [7]:
bus

            표준ID  ARS-ID           정류장명         X좌표        Y좌표
0      100000001    1001        종로2가사거리  126.987750  37.569765
1      100000002    1002    창경궁.서울대학교병원  126.996566  37.579183
2      100000003    1003      명륜3가.성대입구  126.998340  37.582671
3      100000004    1004       종로2가.삼일교  126.987613  37.568579
4      100000005    1005  혜화동로터리.여운형활동터  127.001744  37.586243
...          ...     ...            ...         ...        ...
11275  124000334   25995          우성아파트  127.139339  37.550386
11276  124000333   25996          우성아파트  127.140046  37.550643
11277  124000332   25997           조일약국  127.123596  37.533630
11278  124000331   25998           성내시장  127.125497  37.536155
11279  124000330   25999    천호우체국.로데오거리  127.127337  37.540343

[11280 rows x 5 columns]

In [9]:
bus_df = bus[['표준ID','정류장명', 'X좌표', 'Y좌표']]
bus_df

            표준ID           정류장명         X좌표        Y좌표
0      100000001        종로2가사거리  126.987750  37.569765
1      100000002    창경궁.서울대학교병원  126.996566  37.579183
2      100000003      명륜3가.성대입구  126.998340  37.582671
3      100000004       종로2가.삼일교  126.987613  37.568579
4      100000005  혜화동로터리.여운형활동터  127.001744  37.586243
...          ...            ...         ...        ...
11275  124000334          우성아파트  127.139339  37.550386
11276  124000333          우성아파트  127.140046  37.550643
11277  124000332           조일약국  127.123596  37.533630
11278  124000331           성내시장  127.125497  37.536155
11279  124000330    천호우체국.로데오거리  127.127337  37.540343

[11280 rows x 4 columns]