In [1]:
# 필요한 라이브러리 임포트&설치
# !pip install dbfread
# !pip install haversine
# !pip install sklearn
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from haversine import haversine
from tqdm.notebook import tqdm
%matplotlib inline
import platform
import pickle
import re
platform.system()
if platform.system() == 'Darwin': # Mac 환경 폰트 설정
    plt.rc('font', family='AppleGothic')
elif platform.system() == 'Windows': # Windows 환경 폰트 설정
    plt.rc('font', family='Malgun Gothic')
plt.rc('axes', unicode_minus=False) # 마이너스 폰트 설정
%config InlineBackend.figure_format = 'retina'

In [2]:
def pklopen(route):
    with open('{}'.format(route), 'rb') as f:
        df = pickle.load(f)
    return df
def pklsave(df, name):
    with open('{}.pkl'.format(name), 'wb') as f:
        pickle.dump(df, f)

출처:http://kosis.kr/statisticsList/statisticsListIndex.do?menuId=M_01_01&vwcd=MT_ZTITLE&parmTabId=M_01_01#SelectStatsBoxDiv

In [3]:
#멀티인덱스로 잡혀있고, 컬럼지정이 애매해서 전처리해주는 함수 만들었음.
def prep(name):
    df = pd.read_csv(r'./{}'.format(name), encoding = 'cp949')
    df.reset_index(inplace=True)
    df_need = df.rename(columns=df.iloc[0]).drop(df.index[0])
    return df_need

In [4]:
dong = pd.read_excel(r'./서울시_행정동_법정동_20200814.xlsx')

# 여기부턴 깃헙에 올리기에 데이터가 너무 커서 못돌림. 아래로 가서 표시한곳부터 돌릴것.

In [4]:
df12= prep('101_DT_1B04005N_M_2012.csv')
df13= prep('101_DT_1B04005N_M_2013.csv')
df14= prep('101_DT_1B04005N_M_2014.csv')
df15= prep('101_DT_1B04005N_M_2015.csv')
df16= prep('101_DT_1B04005N_M_2016.csv')
df17= prep('101_DT_1B04005N_M_2017.csv')
df18= prep('101_DT_1B04005N_M_2018.csv')
df19= prep('101_DT_1B04005N_M_2019.csv')
df20= prep('101_DT_1B04005N_M_2020.csv')

C:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3337: DtypeWarning: Columns (4,5,6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [5]:
#아래로 이어붙인 데이터 제작
df_total = pd.concat([df12,df13,df14,df15,df16,df17,df18,df19,df20])
df_total

,C행정구역(동읍면)별,행정구역(동읍면)별,C5세별,5세별,시점,총인구수 (명),남자인구수 (명),여자인구수 (명)
1,'00,전국,'0,계,201207,50851082.0000,25460414.0000,25390668.0000
2,'00,전국,'0,계,201208,50871606.0000,25469682.0000,25401924.0000
3,'00,전국,'0,계,201209,50891223.0000,25478622.0000,25412601.0000
4,'00,전국,'0,계,201210,50912264.0000,25488080.0000,25424184.0000
5,'00,전국,'0,계,201211,50930805.0000,25496262.0000,25434543.0000
...,...,...,...,...,...,...,...,...
673086,'5013062000,예래동,'105,100+,202004,4,0,4
673087,'5013062000,예래동,'105,100+,202005,4,0,4
673088,'5013062000,예래동,'105,100+,202006,4,0,4
673089,'5013062000,예래동,'105,100+,202007,4,0,4
673090,'5013062000,예래동,'105,100+,202008,4,0,4

In [6]:
#클랜징 후 전처리
# df_total['C행정구역(동읍면)별'] = pd.to_numeric(df_total['C행정구역(동읍면)별'].str.lstrip("'")) #정수로바꾸고싶을떄
df_total['C행정구역(동읍면)별'] = df_total['C행정구역(동읍면)별'].str.lstrip("'").astype(str)
df_total['행정구역(동읍면)별'] = df_total['행정구역(동읍면)별'].str.strip()
df_total['C5세별'] = df_total['C5세별'].str.lstrip("'").astype(int)
df_total['5세별'] = df_total['5세별'].astype(str)
df_total['시점'] = df_total['시점'].astype(int)
df_total['총인구수 (명)'] = df_total['총인구수 (명)'].astype(float)
df_total['남자인구수 (명)'] = df_total['남자인구수 (명)'].astype(float)
df_total['여자인구수 (명)'] = df_total['여자인구수 (명)'].astype(float)
df_total

,C행정구역(동읍면)별,행정구역(동읍면)별,C5세별,5세별,시점,총인구수 (명),남자인구수 (명),여자인구수 (명)
1,00,전국,0,계,201207,50851082.0,25460414.0,25390668.0
2,00,전국,0,계,201208,50871606.0,25469682.0,25401924.0
3,00,전국,0,계,201209,50891223.0,25478622.0,25412601.0
4,00,전국,0,계,201210,50912264.0,25488080.0,25424184.0
5,00,전국,0,계,201211,50930805.0,25496262.0,25434543.0
...,...,...,...,...,...,...,...,...
673086,5013062000,예래동,105,100+,202004,4.0,0.0,4.0
673087,5013062000,예래동,105,100+,202005,4.0,0.0,4.0
673088,5013062000,예래동,105,100+,202006,4.0,0.0,4.0
673089,5013062000,예래동,105,100+,202007,4.0,0.0,4.0
673090,5013062000,예래동,105,100+,202008,4.0,0.0,4.0

In [7]:
df_total.columns = ['행정동코드','행정동명','연령코드','연령단위','시점','총인구수','남자인구수','여자인구수']
df_total_need = df_total[['시점','행정동코드','행정동명','연령코드','연령단위','총인구수']]
df_total_need

            시점       행정동코드 행정동명  연령코드  연령단위        총인구수
1       201207          00   전국     0     계  50851082.0
2       201208          00   전국     0     계  50871606.0
3       201209          00   전국     0     계  50891223.0
4       201210          00   전국     0     계  50912264.0
5       201211          00   전국     0     계  50930805.0
...        ...         ...  ...   ...   ...         ...
673086  202004  5013062000  예래동   105  100+         4.0
673087  202005  5013062000  예래동   105  100+         4.0
673088  202006  5013062000  예래동   105  100+         4.0
673089  202007  5013062000  예래동   105  100+         4.0
673090  202008  5013062000  예래동   105  100+         4.0

[8254774 rows x 6 columns]

In [144]:
# df_total_need.to_pickle('전국시계열인구.pkl')

In [29]:
# df_total_need = pklopen('전국시계열인구.pkl')

In [35]:
dong = dong[dong['시도명']=='서울특별시']
dong_df = dong[['시군구명','읍면동명','행정동코드']].fillna(0)
gu_code = dong_df[dong_df.읍면동명==0]
gu_code

     시군구명 읍면동명       행정동코드
0       0    0  1100000000
1     종로구    0  1111000000
95     중구    0  1114000000
188   용산구    0  1117000000
227   성동구    0  1120000000
251   광진구    0  1121500000
267  동대문구    0  1123000000
283   중랑구    0  1126000000
300   성북구    0  1129000000
353   강북구    0  1130500000
368   도봉구    0  1132000000
383   노원구    0  1135000000
404   은평구    0  1138000000
421  서대문구    0  1141000000
449   마포구    0  1144000000
491   양천구    0  1147000000
510   강서구    0  1150000000
544   구로구    0  1153000000
563   금천구    0  1154500000
574  영등포구    0  1156000000
620   동작구    0  1159000000
639   관악구    0  1162000000
661   서초구    0  1165000000
685   강남구    0  1168000000
717   송파구    0  1171000000
748   강동구    0  1174000000

In [36]:
dong_code = dong_df[dong_df.읍면동명!=0].drop_duplicates()
dong_code

    시군구명   읍면동명       행정동코드
2    종로구  청운효자동  1111051500
12   종로구    사직동  1111053000
24   종로구    삼청동  1111054000
31   종로구    부암동  1111055000
34   종로구    평창동  1111056000
..   ...    ...         ...
763  강동구  성내제2동  1174065000
764  강동구  성내제3동  1174066000
765  강동구     길동  1174068500
766  강동구  둔촌제1동  1174069000
767  강동구  둔촌제2동  1174070000

[425 rows x 3 columns]

In [37]:
dong_code_dic = {}
for dong, code in zip(dong_code.읍면동명, dong_code.행정동코드):
    dong_code_dic[dong] = code
dong_code_dic

{'청운효자동': 1111051500,
 '사직동': 1111053000,
 '삼청동': 1111054000,
 '부암동': 1111055000,
 '평창동': 1111056000,
 '무악동': 1111057000,
 '교남동': 1111058000,
 '가회동': 1111060000,
 '종로1.2.3.4가동': 1111061500,
 '종로5.6가동': 1111063000,
 '이화동': 1111064000,
 '혜화동': 1111065000,
 '창신제1동': 1111067000,
 '창신제2동': 1111068000,
 '창신제3동': 1111069000,
 '숭인제1동': 1111070000,
 '숭인제2동': 1111071000,
 '소공동': 1114052000,
 '회현동': 1114054000,
 '명동': 1114055000,
 '필동': 1114057000,
 '장충동': 1114058000,
 '광희동': 1114059000,
 '을지로동': 1114060500,
 '신당동': 1114061500,
 '다산동': 1114062500,
 '약수동': 1114063500,
 '청구동': 1114064500,
 '신당제5동': 1114065000,
 '동화동': 1114066500,
 '황학동': 1114067000,
 '중림동': 1114068000,
 '후암동': 1117051000,
 '용산2가동': 1117052000,
 '남영동': 1117053000,
 '청파동': 1117055500,
 '원효로제1동': 1117056000,
 '원효로제2동': 1117057000,
 '효창동': 1117058000,
 '용문동': 1117059000,
 '한강로동': 1117062500,
 '이촌제1동': 1117063000,
 '이촌제2동': 1117064000,
 '이태원제1동': 1117065000,
 '이태원제2동': 1117066000,
 '한남동': 1117068500,
 '서빙고동': 1117069000,
 '보광동': 1117070000,
 '왕십리제2동': 1120052000,
 '왕십리도선동': 1120053500,
 '마장동': 1120054000,
 '사근동': 1120055000,
 '행당제1동': 1120056000,
 '행당제2동': 1120057000,
 '응봉동': 1120058000,
 '금호1가동': 1120059000,
 '금호2.3가동': 1120061500,
 '금호4가동': 1120062000,
 '옥수동': 1120064500,
 '성수1가제1동': 1120065000,
 '성수1가제2동': 1120066000,
 '성수2가제1동': 1120067000,
 '성수2가제3동': 1120069000,
 '송정동': 1120072000,
 '용답동': 1120079000,
 '화양동': 1121571000,
 '군자동': 1121573000,
 '중곡제1동': 1121574000,
 '중곡제2동': 1121575000,
 '중곡제3동': 1121576000,
 '중곡제4동': 1121577000,
 '능동': 1121578000,
 '광장동': 1121581000,
 '자양제1동': 1121582000,
 '자양제2동': 1121583000,
 '자양제3동': 1121584000,
 '자양제4동': 1121584700,
 '구의제1동': 1121585000,
 '구의제2동': 1121586000,
 '구의제3동': 1121587000,
 '용신동': 1123053600,
 '제기동': 1123054500,
 '전농제1동': 1123056000,
 '전농제2동': 1123057000,
 '답십리제1동': 1123060000,
 '답십리제2동': 1123061000,
 '장안제1동': 1123065000,
 '장안제2동': 1123066000,
 '청량리동': 1123070500,
 '회기동': 1123071000,
 '휘경제1동': 1123072000,
 '휘경제2동': 1123073000,
 '이문제1동': 1123074000,
 '이문제2동': 1123075000,
 '면목제2동': 1126052000,
 '면목제4동': 1126054000,
 '면목제5동': 1126055000,
 '면목본동': 1126056500,
 '면목제7동': 1126057000,
 '면목제3.8동': 1126057500,
 '상봉제1동': 1126058000,
 '상봉제2동': 1126059000,
 '중화제1동': 1126060000,
 '중화제2동': 1126061000,
 '묵제1동': 1126062000,
 '묵제2동': 1126063000,
 '망우본동': 1126065500,
 '망우제3동': 1126066000,
 '신내1동': 1126068000,
 '신내2동': 1126069000,
 '성북동': 1129052500,
 '삼선동': 1129055500,
 '동선동': 1129057500,
 '돈암제1동': 1129058000,
 '돈암제2동': 1129059000,
 '안암동': 1129060000,
 '보문동': 1129061000,
 '정릉제1동': 1129062000,
 '정릉제2동': 1129063000,
 '정릉제3동': 1129064000,
 '정릉제4동': 1129065000,
 '길음제1동': 1129066000,
 '길음제2동': 1129068500,
 '종암동': 1129070500,
 '월곡제1동': 1129071500,
 '월곡제2동': 1129072500,
 '장위제1동': 1129076000,
 '장위제2동': 1129077000,
 '장위제3동': 1129078000,
 '석관동': 1129081000,
 '삼양동': 1130553400,
 '미아동': 1130553500,
 '송중동': 1130554500,
 '송천동': 1130555500,
 '삼각산동': 1130557500,
 '번1동': 1130559500,
 '번2동': 1130560300,
 '번3동': 1130560800,
 '수유1동': 1130561500,
 '수유2동': 1130562500,
 '수유3동': 1130563500,
 '우이동': 1130564500,
 '인수동': 1130566000,
 '창제1동': 1132051100,
 '창제2동': 1132051200,
 '창제3동': 1132051300,
 '창제4동': 1132051400,
 '창제5동': 1132051500,
 '도봉제1동': 1132052100,
 '도봉제2동': 1132052200,
 '쌍문제1동': 1132066000,
 '쌍문제2동': 1132067000,
 '쌍문제3동': 1132068000,
 '쌍문제4동': 1132068100,
 '방학제1동': 1132069000,
 '방학제2동': 1132070000,
 '방학제3동': 1132071000,
 '월계1동': 1135056000,
 '월계2동': 1135057000,
 '월계3동': 1135058000,
 '공릉1동': 1135059500,
 '공릉2동': 1135060000,
 '하계1동': 1135061100,
 '하계2동': 1135061200,
 '중계본동': 1135061900,
 '중계1동': 1135062100,
 '중계4동': 1135062400,
 '중계2.3동': 1135062500,
 '상계1동': 1135063000,
 '상계2동': 1135064000,
 '상계3.4동': 1135066500,
 '상계5동': 1135067000,
 '상계6.7동': 1135069500,
 '상계8동': 1135070000,
 '상계9동': 1135071000,
 '상계10동': 1135072000,
 '녹번동': 1138051000,
 '불광제1동': 1138052000,
 '불광제2동': 1138053000,
 '갈현제1동': 1138055100,
 '갈현제2동': 1138055200,
 '구산동': 1138056000,
 '대조동': 1138057000,
 '응암제1동': 1138058000,
 '응암제2동': 1138059000,
 '응암제3동': 1138060000,
 '역촌동': 1138062500,
 '신사제1동': 1138063100,
 '신사제2동': 1138063200,
 '증산동': 1138064000,
 '수색동': 1138065000,
 '진관동': 1138069000,
 '천연동': 1141052000,
 '북아현동': 1141055500,
 '충현동': 1141056500,
 '신촌동': 1141058500,
 '연희동': 1141061500,
 '홍제제1동': 1141062000,
 '홍제제3동': 1141064000,
 '홍제제2동': 1141065500,
 '홍은제1동': 1141066000,
 '홍은제2동': 1141068500,
 '남가좌제1동': 1141069000,
 '남가좌제2동': 1141070000,
 '북가좌제1동': 1141071000,
 '북가좌제2동': 1141072000,
 '아현동': 1144055500,
 '공덕동': 1144056500,
 '도화동': 1144058500,
 '용강동': 1144059000,
 '대흥동': 1144060000,
 '염리동': 1144061000,
 '신수동': 1144063000,
 '서강동': 1144065500,
 '서교동': 1144066000,
 '합정동': 1144068000,
 '망원제1동': 1144069000,
 '망원제2동': 1144070000,
 '연남동': 1144071000,
 '성산제1동': 1144072000,
 '성산제2동': 1144073000,
 '상암동': 1144074000,
 '목1동': 1147051000,
 '목2동': 1147052000,
 '목3동': 1147053000,
 '목4동': 1147054000,
 '목5동': 1147055000,
 '신월1동': 1147056000,
 '신월2동': 1147057000,
 '신월3동': 1147058000,
 '신월4동': 1147059000,
 '신월5동': 1147060000,
 '신월6동': 1147061000,
 '신월7동': 1147061100,
 '신정1동': 1147062000,
 '신정2동': 1147063000,
 '신정3동': 1147064000,
 '신정4동': 1147065000,
 '신정6동': 1147067000,
 '신정7동': 1147068000,
 '염창동': 1150051000,
 '등촌제1동': 1150052000,
 '등촌제2동': 1150053000,
 '등촌제3동': 1150053500,
 '화곡제1동': 1150054000,
 '화곡제2동': 1150055000,
 '화곡제3동': 1150056000,
 '화곡제4동': 1150057000,
 '화곡본동': 1150059000,
 '화곡제6동': 1150059100,
 '화곡제8동': 1150059300,
 '가양제1동': 1150060300,
 '가양제2동': 1150060400,
 '가양제3동': 1150060500,
 '발산제1동': 1150061100,
 '우장산동': 1150061500,
 '공항동': 1150062000,
 '방화제1동': 1150063000,
 '방화제2동': 1150064000,
 '방화제3동': 1150064100,
 '신도림동': 1153051000,
 '구로제1동': 1153052000,
 '구로제2동': 1153053000,
 '구로제3동': 1153054000,
 '구로제4동': 1153055000,
 '구로제5동': 1153056000,
 '가리봉동': 1153059500,
 '고척제1동': 1153072000,
 '고척제2동': 1153073000,
 '개봉제1동': 1153074000,
 '개봉제2동': 1153075000,
 '개봉제3동': 1153076000,
 '오류제1동': 1153077000,
 '오류제2동': 1153078000,
 '수궁동': 1153079000,
 '항동': 1153080000,
 '가산동': 1154551000,
 '독산제1동': 1154561000,
 '독산제2동': 1154562000,
 '독산제3동': 1154563000,
 '독산제4동': 1154564000,
 '시흥제1동': 1154567000,
 '시흥제2동': 1154568000,
 '시흥제3동': 1154569000,
 '시흥제4동': 1154570000,
 '시흥제5동': 1154571000,
 '영등포본동': 1156051500,
 '영등포동': 1156053500,
 '여의동': 1156054000,
 '당산제1동': 1156055000,
 '당산제2동': 1156056000,
 '도림동': 1156058500,
 '문래동': 1156060500,
 '양평제1동': 1156061000,
 '양평제2동': 1156062000,
 '신길제1동': 1156063000,
 '신길제3동': 1156065000,
 '신길제4동': 1156066000,
 '신길제5동': 1156067000,
 '신길제6동': 1156068000,
 '신길제7동': 1156069000,
 '대림제1동': 1156070000,
 '대림제2동': 1156071000,
 '대림제3동': 1156072000,
 '노량진제1동': 1159051000,
 '노량진제2동': 1159052000,
 '상도제1동': 1159053000,
 '상도제2동': 1159054000,
 '상도제3동': 1159055000,
 '상도제4동': 1159056000,
 '흑석동': 1159060500,
 '사당제1동': 1159062000,
 '사당제2동': 1159063000,
 '사당제3동': 1159064000,
 '사당제4동': 1159065000,
 '사당제5동': 1159065100,
 '대방동': 1159066000,
 '신대방제1동': 1159067000,
 '신대방제2동': 1159068000,
 '보라매동': 1162052500,
 '청림동': 1162054500,
 '성현동': 1162056500,
 '행운동': 1162057500,
 '낙성대동': 1162058500,
 '청룡동': 1162059500,
 '은천동': 1162060500,
 '중앙동': 1162061500,
 '인헌동': 1162062500,
 '남현동': 1162063000,
 '서원동': 1162064500,
 '신원동': 1162065500,
 '서림동': 1162066500,
 '신사동': 1168051000,
 '신림동': 1162069500,
 '난향동': 1162071500,
 '조원동': 1162072500,
 '대학동': 1162073500,
 '삼성동': 1162074500,
 '미성동': 1162076500,
 '난곡동': 1162077500,
 '서초1동': 1165051000,
 '서초2동': 1165052000,
 '서초3동': 1165053000,
 '서초4동': 1165053100,
 '잠원동': 1165054000,
 '반포본동': 1165055000,
 '반포1동': 1165056000,
 '반포2동': 1165057000,
 '반포3동': 1165058000,
 '반포4동': 1165058100,
 '방배본동': 1165059000,
 '방배1동': 1165060000,
 '방배2동': 1165061000,
 '방배3동': 1165062000,
 '방배4동': 1165062100,
 '양재1동': 1165065100,
 '양재2동': 1165065200,
 '내곡동': 1165066000,
 '논현1동': 1168052100,
 '논현2동': 1168053100,
 '압구정동': 1168054500,
 '청담동': 1168056500,
 '삼성1동': 1168058000,
 '삼성2동': 1168059000,
 '대치1동': 1168060000,
 '대치2동': 1168061000,
 '대치4동': 1168063000,
 '역삼1동': 1168064000,
 '역삼2동': 1168065000,
 '도곡1동': 1168065500,
 '도곡2동': 1168065600,
 '개포1동': 1168066000,
 '개포2동': 1168067000,
 '개포4동': 1168069000,
 '세곡동': 1168070000,
 '일원본동': 1168072000,
 '일원1동': 1168073000,
 '일원2동': 1168074000,
 '수서동': 1168075000,
 '풍납1동': 1171051000,
 '풍납2동': 1171052000,
 '거여1동': 1171053100,
 '거여2동': 1171053200,
 '마천1동': 1171054000,
 '마천2동': 1171055000,
 '방이1동': 1171056100,
 '방이2동': 1171056200,
 '오륜동': 1171056600,
 '오금동': 1171057000,
 '송파1동': 1171058000,
 '송파2동': 1171059000,
 '석촌동': 1171060000,
 '삼전동': 1171061000,
 '가락본동': 1171062000,
 '가락1동': 1171063100,
 '가락2동': 1171063200,
 '문정1동': 1171064100,
 '문정2동': 1171064200,
 '장지동': 1171064600,
 '위례동': 1171064700,
 '잠실본동': 1171065000,
 '잠실2동': 1171067000,
 '잠실3동': 1171068000,
 '잠실4동': 1171069000,
 '잠실6동': 1171071000,
 '잠실7동': 1171072000,
 '강일동': 1174051500,
 '상일동': 1174052000,
 '명일제1동': 1174053000,
 '명일제2동': 1174054000,
 '고덕제1동': 1174055000,
 '고덕제2동': 1174056000,
 '암사제1동': 1174057000,
 '암사제2동': 1174058000,
 '암사제3동': 1174059000,
 '천호제1동': 1174060000,
 '천호제2동': 1174061000,
 '천호제3동': 1174062000,
 '성내제1동': 1174064000,
 '성내제2동': 1174065000,
 '성내제3동': 1174066000,
 '길동': 1174068500,
 '둔촌제1동': 1174069000,
 '둔촌제2동': 1174070000}

In [38]:
dong_code_list = list(dong_code.행정동코드)
dong_code_list

[1111051500,
 1111053000,
 1111054000,
 1111055000,
 1111056000,
 1111057000,
 1111058000,
 1111060000,
 1111061500,
 1111063000,
 1111064000,
 1111065000,
 1111067000,
 1111068000,
 1111069000,
 1111070000,
 1111071000,
 1114052000,
 1114054000,
 1114055000,
 1114057000,
 1114058000,
 1114059000,
 1114060500,
 1114061500,
 1114062500,
 1114063500,
 1114064500,
 1114065000,
 1114066500,
 1114067000,
 1114068000,
 1117051000,
 1117052000,
 1117053000,
 1117055500,
 1117056000,
 1117057000,
 1117058000,
 1117059000,
 1117062500,
 1117063000,
 1117064000,
 1117065000,
 1117066000,
 1117068500,
 1117069000,
 1117070000,
 1120052000,
 1120053500,
 1120054000,
 1120055000,
 1120056000,
 1120057000,
 1120058000,
 1120059000,
 1120061500,
 1120062000,
 1120064500,
 1120065000,
 1120066000,
 1120067000,
 1120069000,
 1120072000,
 1120079000,
 1121571000,
 1121573000,
 1121574000,
 1121575000,
 1121576000,
 1121577000,
 1121578000,
 1121581000,
 1121582000,
 1121583000,
 1121584000,
 1121584700,
 1121585000,
 1121586000,
 1121587000,
 1123053600,
 1123054500,
 1123056000,
 1123057000,
 1123060000,
 1123061000,
 1123065000,
 1123066000,
 1123070500,
 1123071000,
 1123072000,
 1123073000,
 1123074000,
 1123075000,
 1126052000,
 1126054000,
 1126055000,
 1126056500,
 1126057000,
 1126057500,
 1126058000,
 1126059000,
 1126060000,
 1126061000,
 1126062000,
 1126063000,
 1126065500,
 1126066000,
 1126068000,
 1126069000,
 1129052500,
 1129055500,
 1129057500,
 1129058000,
 1129059000,
 1129060000,
 1129061000,
 1129062000,
 1129063000,
 1129064000,
 1129065000,
 1129066000,
 1129068500,
 1129070500,
 1129071500,
 1129072500,
 1129076000,
 1129077000,
 1129078000,
 1129081000,
 1130553400,
 1130553500,
 1130554500,
 1130555500,
 1130557500,
 1130559500,
 1130560300,
 1130560800,
 1130561500,
 1130562500,
 1130563500,
 1130564500,
 1130566000,
 1132051100,
 1132051200,
 1132051300,
 1132051400,
 1132051500,
 1132052100,
 1132052200,
 1132066000,
 1132067000,
 1132068000,
 1132068100,
 1132069000,
 1132070000,
 1132071000,
 1135056000,
 1135057000,
 1135058000,
 1135059500,
 1135060000,
 1135061100,
 1135061200,
 1135061900,
 1135062100,
 1135062400,
 1135062500,
 1135063000,
 1135064000,
 1135066500,
 1135067000,
 1135069500,
 1135070000,
 1135071000,
 1135072000,
 1138051000,
 1138052000,
 1138053000,
 1138055100,
 1138055200,
 1138056000,
 1138057000,
 1138058000,
 1138059000,
 1138060000,
 1138062500,
 1138063100,
 1138063200,
 1138064000,
 1138065000,
 1138069000,
 1141052000,
 1141055500,
 1141056500,
 1141058500,
 1141061500,
 1141062000,
 1141064000,
 1141065500,
 1141066000,
 1141068500,
 1141069000,
 1141070000,
 1141071000,
 1141072000,
 1144055500,
 1144056500,
 1144058500,
 1144059000,
 1144060000,
 1144061000,
 1144063000,
 1144065500,
 1144066000,
 1144068000,
 1144069000,
 1144070000,
 1144071000,
 1144072000,
 1144073000,
 1144074000,
 1147051000,
 1147052000,
 1147053000,
 1147054000,
 1147055000,
 1147056000,
 1147057000,
 1147058000,
 1147059000,
 1147060000,
 1147061000,
 1147061100,
 1147062000,
 1147063000,
 1147064000,
 1147065000,
 1147067000,
 1147068000,
 1150051000,
 1150052000,
 1150053000,
 1150053500,
 1150054000,
 1150055000,
 1150056000,
 1150057000,
 1150059000,
 1150059100,
 1150059300,
 1150060300,
 1150060400,
 1150060500,
 1150061100,
 1150061500,
 1150062000,
 1150063000,
 1150064000,
 1150064100,
 1153051000,
 1153052000,
 1153053000,
 1153054000,
 1153055000,
 1153056000,
 1153059500,
 1153072000,
 1153073000,
 1153074000,
 1153075000,
 1153076000,
 1153077000,
 1153078000,
 1153079000,
 1153080000,
 1154551000,
 1154561000,
 1154562000,
 1154563000,
 1154564000,
 1154567000,
 1154568000,
 1154569000,
 1154570000,
 1154571000,
 1156051500,
 1156053500,
 1156054000,
 1156055000,
 1156056000,
 1156058500,
 1156060500,
 1156061000,
 1156062000,
 1156063000,
 1156065000,
 1156066000,
 1156067000,
 1156068000,
 1156069000,
 1156070000,
 1156071000,
 1156072000,
 1159051000,
 1159052000,
 1159053000,
 1159054000,
 1159055000,
 1159056000,
 1159060500,
 1159062000,
 1159063000,
 1159064000,
 1159065000,
 1159065100,
 1159066000,
 1159067000,
 1159068000,
 1162052500,
 1162054500,
 1162056500,
 1162057500,
 1162058500,
 1162059500,
 1162060500,
 1162061500,
 1162062500,
 1162063000,
 1162064500,
 1162065500,
 1162066500,
 1162068500,
 1162069500,
 1162071500,
 1162072500,
 1162073500,
 1162074500,
 1162076500,
 1162077500,
 1165051000,
 1165052000,
 1165053000,
 1165053100,
 1165054000,
 1165055000,
 1165056000,
 1165057000,
 1165058000,
 1165058100,
 1165059000,
 1165060000,
 1165061000,
 1165062000,
 1165062100,
 1165065100,
 1165065200,
 1165066000,
 1168051000,
 1168052100,
 1168053100,
 1168054500,
 1168056500,
 1168058000,
 1168059000,
 1168060000,
 1168061000,
 1168063000,
 1168064000,
 1168065000,
 1168065500,
 1168065600,
 1168066000,
 1168067000,
 1168069000,
 1168070000,
 1168072000,
 1168073000,
 1168074000,
 1168075000,
 1171051000,
 1171052000,
 1171053100,
 1171053200,
 1171054000,
 1171055000,
 1171056100,
 1171056200,
 1171056600,
 1171057000,
 1171058000,
 1171059000,
 1171060000,
 1171061000,
 1171062000,
 1171063100,
 1171063200,
 1171064100,
 1171064200,
 1171064600,
 1171064700,
 1171065000,
 1171067000,
 1171068000,
 1171069000,
 1171071000,
 1171072000,
 1174051500,
 1174052000,
 1174053000,
 1174054000,
 1174055000,
 1174056000,
 1174057000,
 1174058000,
 1174059000,
 1174060000,
 1174061000,
 1174062000,
 1174064000,
 1174065000,
 1174066000,
 1174068500,
 1174069000,
 1174070000]

In [60]:
for key, value in dong_code_dic.items():
    df_ = df_total_need[df_total_need.행정동코드 == str(value)]
#     pklsave(df_, '{} 연령별인구'.format(key))

    break
df_

         시점       행정동코드   행정동명  연령코드  연령단위     총인구수
397  201207  1111051500  청운효자동     0     계  15216.0
398  201208  1111051500  청운효자동     0     계  15234.0
399  201209  1111051500  청운효자동     0     계  15195.0
400  201210  1111051500  청운효자동     0     계  15175.0
401  201211  1111051500  청운효자동     0     계  15160.0
..      ...         ...    ...   ...   ...      ...
700  202004  1111051500  청운효자동   105  100+     19.0
701  202005  1111051500  청운효자동   105  100+     19.0
702  202006  1111051500  청운효자동   105  100+     19.0
703  202007  1111051500  청운효자동   105  100+     19.0
704  202008  1111051500  청운효자동   105  100+     19.0

[2156 rows x 6 columns]

In [61]:
data_df = df_total_need[df_total_need.행정동코드 == 0]
pd.concat([data_df, df_])

         시점       행정동코드   행정동명  연령코드  연령단위     총인구수
397  201207  1111051500  청운효자동     0     계  15216.0
398  201208  1111051500  청운효자동     0     계  15234.0
399  201209  1111051500  청운효자동     0     계  15195.0
400  201210  1111051500  청운효자동     0     계  15175.0
401  201211  1111051500  청운효자동     0     계  15160.0
..      ...         ...    ...   ...   ...      ...
700  202004  1111051500  청운효자동   105  100+     19.0
701  202005  1111051500  청운효자동   105  100+     19.0
702  202006  1111051500  청운효자동   105  100+     19.0
703  202007  1111051500  청운효자동   105  100+     19.0
704  202008  1111051500  청운효자동   105  100+     19.0

[2156 rows x 6 columns]

In [68]:
data_df = df_total_need[df_total_need.행정동코드 == 0]
for key, value in dong_code_dic.items():
    df_ = df_total_need[df_total_need.행정동코드 == str(value)]
    data_df = pd.concat([data_df, df_])
data_df

           시점       행정동코드   행정동명  연령코드  연령단위     총인구수
397    201207  1111051500  청운효자동     0     계  15216.0
398    201208  1111051500  청운효자동     0     계  15234.0
399    201209  1111051500  청운효자동     0     계  15195.0
400    201210  1111051500  청운효자동     0     계  15175.0
401    201211  1111051500  청운효자동     0     계  15160.0
...       ...         ...    ...   ...   ...      ...
79548  202004  1174070000  둔촌제2동   105  100+     13.0
79549  202005  1174070000  둔촌제2동   105  100+     12.0
79550  202006  1174070000  둔촌제2동   105  100+     12.0
79551  202007  1174070000  둔촌제2동   105  100+     12.0
79552  202008  1174070000  둔촌제2동   105  100+     13.0

[899756 rows x 6 columns]

In [69]:
data_df.to_pickle('연령별인구데이터.pkl')

# 여기부터 돌리기

In [6]:
dong = dong[dong['시도명']=='서울특별시']
dong_df = dong[['시군구명','읍면동명','행정동코드']].fillna(0)
gu_code = dong_df[dong_df.읍면동명==0]
gu_code

     시군구명 읍면동명       행정동코드
0       0    0  1100000000
1     종로구    0  1111000000
95     중구    0  1114000000
188   용산구    0  1117000000
227   성동구    0  1120000000
251   광진구    0  1121500000
267  동대문구    0  1123000000
283   중랑구    0  1126000000
300   성북구    0  1129000000
353   강북구    0  1130500000
368   도봉구    0  1132000000
383   노원구    0  1135000000
404   은평구    0  1138000000
421  서대문구    0  1141000000
449   마포구    0  1144000000
491   양천구    0  1147000000
510   강서구    0  1150000000
544   구로구    0  1153000000
563   금천구    0  1154500000
574  영등포구    0  1156000000
620   동작구    0  1159000000
639   관악구    0  1162000000
661   서초구    0  1165000000
685   강남구    0  1168000000
717   송파구    0  1171000000
748   강동구    0  1174000000

In [7]:
dong_code = dong_df[dong_df.읍면동명!=0].drop_duplicates()
dong_code

    시군구명   읍면동명       행정동코드
2    종로구  청운효자동  1111051500
12   종로구    사직동  1111053000
24   종로구    삼청동  1111054000
31   종로구    부암동  1111055000
34   종로구    평창동  1111056000
..   ...    ...         ...
763  강동구  성내제2동  1174065000
764  강동구  성내제3동  1174066000
765  강동구     길동  1174068500
766  강동구  둔촌제1동  1174069000
767  강동구  둔촌제2동  1174070000

[425 rows x 3 columns]

In [8]:
dong_code_dic = {}
for dong, code in zip(dong_code.읍면동명, dong_code.행정동코드):
    dong_code_dic[dong] = code
dong_code_dic

{'청운효자동': 1111051500,
 '사직동': 1111053000,
 '삼청동': 1111054000,
 '부암동': 1111055000,
 '평창동': 1111056000,
 '무악동': 1111057000,
 '교남동': 1111058000,
 '가회동': 1111060000,
 '종로1.2.3.4가동': 1111061500,
 '종로5.6가동': 1111063000,
 '이화동': 1111064000,
 '혜화동': 1111065000,
 '창신제1동': 1111067000,
 '창신제2동': 1111068000,
 '창신제3동': 1111069000,
 '숭인제1동': 1111070000,
 '숭인제2동': 1111071000,
 '소공동': 1114052000,
 '회현동': 1114054000,
 '명동': 1114055000,
 '필동': 1114057000,
 '장충동': 1114058000,
 '광희동': 1114059000,
 '을지로동': 1114060500,
 '신당동': 1114061500,
 '다산동': 1114062500,
 '약수동': 1114063500,
 '청구동': 1114064500,
 '신당제5동': 1114065000,
 '동화동': 1114066500,
 '황학동': 1114067000,
 '중림동': 1114068000,
 '후암동': 1117051000,
 '용산2가동': 1117052000,
 '남영동': 1117053000,
 '청파동': 1117055500,
 '원효로제1동': 1117056000,
 '원효로제2동': 1117057000,
 '효창동': 1117058000,
 '용문동': 1117059000,
 '한강로동': 1117062500,
 '이촌제1동': 1117063000,
 '이촌제2동': 1117064000,
 '이태원제1동': 1117065000,
 '이태원제2동': 1117066000,
 '한남동': 1117068500,
 '서빙고동': 1117069000,
 '보광동': 1117070000,
 '왕십리제2동': 1120052000,
 '왕십리도선동': 1120053500,
 '마장동': 1120054000,
 '사근동': 1120055000,
 '행당제1동': 1120056000,
 '행당제2동': 1120057000,
 '응봉동': 1120058000,
 '금호1가동': 1120059000,
 '금호2.3가동': 1120061500,
 '금호4가동': 1120062000,
 '옥수동': 1120064500,
 '성수1가제1동': 1120065000,
 '성수1가제2동': 1120066000,
 '성수2가제1동': 1120067000,
 '성수2가제3동': 1120069000,
 '송정동': 1120072000,
 '용답동': 1120079000,
 '화양동': 1121571000,
 '군자동': 1121573000,
 '중곡제1동': 1121574000,
 '중곡제2동': 1121575000,
 '중곡제3동': 1121576000,
 '중곡제4동': 1121577000,
 '능동': 1121578000,
 '광장동': 1121581000,
 '자양제1동': 1121582000,
 '자양제2동': 1121583000,
 '자양제3동': 1121584000,
 '자양제4동': 1121584700,
 '구의제1동': 1121585000,
 '구의제2동': 1121586000,
 '구의제3동': 1121587000,
 '용신동': 1123053600,
 '제기동': 1123054500,
 '전농제1동': 1123056000,
 '전농제2동': 1123057000,
 '답십리제1동': 1123060000,
 '답십리제2동': 1123061000,
 '장안제1동': 1123065000,
 '장안제2동': 1123066000,
 '청량리동': 1123070500,
 '회기동': 1123071000,
 '휘경제1동': 1123072000,
 '휘경제2동': 1123073000,
 '이문제1동': 1123074000,
 '이문제2동': 1123075000,
 '면목제2동': 1126052000,
 '면목제4동': 1126054000,
 '면목제5동': 1126055000,
 '면목본동': 1126056500,
 '면목제7동': 1126057000,
 '면목제3.8동': 1126057500,
 '상봉제1동': 1126058000,
 '상봉제2동': 1126059000,
 '중화제1동': 1126060000,
 '중화제2동': 1126061000,
 '묵제1동': 1126062000,
 '묵제2동': 1126063000,
 '망우본동': 1126065500,
 '망우제3동': 1126066000,
 '신내1동': 1126068000,
 '신내2동': 1126069000,
 '성북동': 1129052500,
 '삼선동': 1129055500,
 '동선동': 1129057500,
 '돈암제1동': 1129058000,
 '돈암제2동': 1129059000,
 '안암동': 1129060000,
 '보문동': 1129061000,
 '정릉제1동': 1129062000,
 '정릉제2동': 1129063000,
 '정릉제3동': 1129064000,
 '정릉제4동': 1129065000,
 '길음제1동': 1129066000,
 '길음제2동': 1129068500,
 '종암동': 1129070500,
 '월곡제1동': 1129071500,
 '월곡제2동': 1129072500,
 '장위제1동': 1129076000,
 '장위제2동': 1129077000,
 '장위제3동': 1129078000,
 '석관동': 1129081000,
 '삼양동': 1130553400,
 '미아동': 1130553500,
 '송중동': 1130554500,
 '송천동': 1130555500,
 '삼각산동': 1130557500,
 '번1동': 1130559500,
 '번2동': 1130560300,
 '번3동': 1130560800,
 '수유1동': 1130561500,
 '수유2동': 1130562500,
 '수유3동': 1130563500,
 '우이동': 1130564500,
 '인수동': 1130566000,
 '창제1동': 1132051100,
 '창제2동': 1132051200,
 '창제3동': 1132051300,
 '창제4동': 1132051400,
 '창제5동': 1132051500,
 '도봉제1동': 1132052100,
 '도봉제2동': 1132052200,
 '쌍문제1동': 1132066000,
 '쌍문제2동': 1132067000,
 '쌍문제3동': 1132068000,
 '쌍문제4동': 1132068100,
 '방학제1동': 1132069000,
 '방학제2동': 1132070000,
 '방학제3동': 1132071000,
 '월계1동': 1135056000,
 '월계2동': 1135057000,
 '월계3동': 1135058000,
 '공릉1동': 1135059500,
 '공릉2동': 1135060000,
 '하계1동': 1135061100,
 '하계2동': 1135061200,
 '중계본동': 1135061900,
 '중계1동': 1135062100,
 '중계4동': 1135062400,
 '중계2.3동': 1135062500,
 '상계1동': 1135063000,
 '상계2동': 1135064000,
 '상계3.4동': 1135066500,
 '상계5동': 1135067000,
 '상계6.7동': 1135069500,
 '상계8동': 1135070000,
 '상계9동': 1135071000,
 '상계10동': 1135072000,
 '녹번동': 1138051000,
 '불광제1동': 1138052000,
 '불광제2동': 1138053000,
 '갈현제1동': 1138055100,
 '갈현제2동': 1138055200,
 '구산동': 1138056000,
 '대조동': 1138057000,
 '응암제1동': 1138058000,
 '응암제2동': 1138059000,
 '응암제3동': 1138060000,
 '역촌동': 1138062500,
 '신사제1동': 1138063100,
 '신사제2동': 1138063200,
 '증산동': 1138064000,
 '수색동': 1138065000,
 '진관동': 1138069000,
 '천연동': 1141052000,
 '북아현동': 1141055500,
 '충현동': 1141056500,
 '신촌동': 1141058500,
 '연희동': 1141061500,
 '홍제제1동': 1141062000,
 '홍제제3동': 1141064000,
 '홍제제2동': 1141065500,
 '홍은제1동': 1141066000,
 '홍은제2동': 1141068500,
 '남가좌제1동': 1141069000,
 '남가좌제2동': 1141070000,
 '북가좌제1동': 1141071000,
 '북가좌제2동': 1141072000,
 '아현동': 1144055500,
 '공덕동': 1144056500,
 '도화동': 1144058500,
 '용강동': 1144059000,
 '대흥동': 1144060000,
 '염리동': 1144061000,
 '신수동': 1144063000,
 '서강동': 1144065500,
 '서교동': 1144066000,
 '합정동': 1144068000,
 '망원제1동': 1144069000,
 '망원제2동': 1144070000,
 '연남동': 1144071000,
 '성산제1동': 1144072000,
 '성산제2동': 1144073000,
 '상암동': 1144074000,
 '목1동': 1147051000,
 '목2동': 1147052000,
 '목3동': 1147053000,
 '목4동': 1147054000,
 '목5동': 1147055000,
 '신월1동': 1147056000,
 '신월2동': 1147057000,
 '신월3동': 1147058000,
 '신월4동': 1147059000,
 '신월5동': 1147060000,
 '신월6동': 1147061000,
 '신월7동': 1147061100,
 '신정1동': 1147062000,
 '신정2동': 1147063000,
 '신정3동': 1147064000,
 '신정4동': 1147065000,
 '신정6동': 1147067000,
 '신정7동': 1147068000,
 '염창동': 1150051000,
 '등촌제1동': 1150052000,
 '등촌제2동': 1150053000,
 '등촌제3동': 1150053500,
 '화곡제1동': 1150054000,
 '화곡제2동': 1150055000,
 '화곡제3동': 1150056000,
 '화곡제4동': 1150057000,
 '화곡본동': 1150059000,
 '화곡제6동': 1150059100,
 '화곡제8동': 1150059300,
 '가양제1동': 1150060300,
 '가양제2동': 1150060400,
 '가양제3동': 1150060500,
 '발산제1동': 1150061100,
 '우장산동': 1150061500,
 '공항동': 1150062000,
 '방화제1동': 1150063000,
 '방화제2동': 1150064000,
 '방화제3동': 1150064100,
 '신도림동': 1153051000,
 '구로제1동': 1153052000,
 '구로제2동': 1153053000,
 '구로제3동': 1153054000,
 '구로제4동': 1153055000,
 '구로제5동': 1153056000,
 '가리봉동': 1153059500,
 '고척제1동': 1153072000,
 '고척제2동': 1153073000,
 '개봉제1동': 1153074000,
 '개봉제2동': 1153075000,
 '개봉제3동': 1153076000,
 '오류제1동': 1153077000,
 '오류제2동': 1153078000,
 '수궁동': 1153079000,
 '항동': 1153080000,
 '가산동': 1154551000,
 '독산제1동': 1154561000,
 '독산제2동': 1154562000,
 '독산제3동': 1154563000,
 '독산제4동': 1154564000,
 '시흥제1동': 1154567000,
 '시흥제2동': 1154568000,
 '시흥제3동': 1154569000,
 '시흥제4동': 1154570000,
 '시흥제5동': 1154571000,
 '영등포본동': 1156051500,
 '영등포동': 1156053500,
 '여의동': 1156054000,
 '당산제1동': 1156055000,
 '당산제2동': 1156056000,
 '도림동': 1156058500,
 '문래동': 1156060500,
 '양평제1동': 1156061000,
 '양평제2동': 1156062000,
 '신길제1동': 1156063000,
 '신길제3동': 1156065000,
 '신길제4동': 1156066000,
 '신길제5동': 1156067000,
 '신길제6동': 1156068000,
 '신길제7동': 1156069000,
 '대림제1동': 1156070000,
 '대림제2동': 1156071000,
 '대림제3동': 1156072000,
 '노량진제1동': 1159051000,
 '노량진제2동': 1159052000,
 '상도제1동': 1159053000,
 '상도제2동': 1159054000,
 '상도제3동': 1159055000,
 '상도제4동': 1159056000,
 '흑석동': 1159060500,
 '사당제1동': 1159062000,
 '사당제2동': 1159063000,
 '사당제3동': 1159064000,
 '사당제4동': 1159065000,
 '사당제5동': 1159065100,
 '대방동': 1159066000,
 '신대방제1동': 1159067000,
 '신대방제2동': 1159068000,
 '보라매동': 1162052500,
 '청림동': 1162054500,
 '성현동': 1162056500,
 '행운동': 1162057500,
 '낙성대동': 1162058500,
 '청룡동': 1162059500,
 '은천동': 1162060500,
 '중앙동': 1162061500,
 '인헌동': 1162062500,
 '남현동': 1162063000,
 '서원동': 1162064500,
 '신원동': 1162065500,
 '서림동': 1162066500,
 '신사동': 1168051000,
 '신림동': 1162069500,
 '난향동': 1162071500,
 '조원동': 1162072500,
 '대학동': 1162073500,
 '삼성동': 1162074500,
 '미성동': 1162076500,
 '난곡동': 1162077500,
 '서초1동': 1165051000,
 '서초2동': 1165052000,
 '서초3동': 1165053000,
 '서초4동': 1165053100,
 '잠원동': 1165054000,
 '반포본동': 1165055000,
 '반포1동': 1165056000,
 '반포2동': 1165057000,
 '반포3동': 1165058000,
 '반포4동': 1165058100,
 '방배본동': 1165059000,
 '방배1동': 1165060000,
 '방배2동': 1165061000,
 '방배3동': 1165062000,
 '방배4동': 1165062100,
 '양재1동': 1165065100,
 '양재2동': 1165065200,
 '내곡동': 1165066000,
 '논현1동': 1168052100,
 '논현2동': 1168053100,
 '압구정동': 1168054500,
 '청담동': 1168056500,
 '삼성1동': 1168058000,
 '삼성2동': 1168059000,
 '대치1동': 1168060000,
 '대치2동': 1168061000,
 '대치4동': 1168063000,
 '역삼1동': 1168064000,
 '역삼2동': 1168065000,
 '도곡1동': 1168065500,
 '도곡2동': 1168065600,
 '개포1동': 1168066000,
 '개포2동': 1168067000,
 '개포4동': 1168069000,
 '세곡동': 1168070000,
 '일원본동': 1168072000,
 '일원1동': 1168073000,
 '일원2동': 1168074000,
 '수서동': 1168075000,
 '풍납1동': 1171051000,
 '풍납2동': 1171052000,
 '거여1동': 1171053100,
 '거여2동': 1171053200,
 '마천1동': 1171054000,
 '마천2동': 1171055000,
 '방이1동': 1171056100,
 '방이2동': 1171056200,
 '오륜동': 1171056600,
 '오금동': 1171057000,
 '송파1동': 1171058000,
 '송파2동': 1171059000,
 '석촌동': 1171060000,
 '삼전동': 1171061000,
 '가락본동': 1171062000,
 '가락1동': 1171063100,
 '가락2동': 1171063200,
 '문정1동': 1171064100,
 '문정2동': 1171064200,
 '장지동': 1171064600,
 '위례동': 1171064700,
 '잠실본동': 1171065000,
 '잠실2동': 1171067000,
 '잠실3동': 1171068000,
 '잠실4동': 1171069000,
 '잠실6동': 1171071000,
 '잠실7동': 1171072000,
 '강일동': 1174051500,
 '상일동': 1174052000,
 '명일제1동': 1174053000,
 '명일제2동': 1174054000,
 '고덕제1동': 1174055000,
 '고덕제2동': 1174056000,
 '암사제1동': 1174057000,
 '암사제2동': 1174058000,
 '암사제3동': 1174059000,
 '천호제1동': 1174060000,
 '천호제2동': 1174061000,
 '천호제3동': 1174062000,
 '성내제1동': 1174064000,
 '성내제2동': 1174065000,
 '성내제3동': 1174066000,
 '길동': 1174068500,
 '둔촌제1동': 1174069000,
 '둔촌제2동': 1174070000}

In [9]:
dong_code_list = list(dong_code.행정동코드)
dong_code_list

[1111051500,
 1111053000,
 1111054000,
 1111055000,
 1111056000,
 1111057000,
 1111058000,
 1111060000,
 1111061500,
 1111063000,
 1111064000,
 1111065000,
 1111067000,
 1111068000,
 1111069000,
 1111070000,
 1111071000,
 1114052000,
 1114054000,
 1114055000,
 1114057000,
 1114058000,
 1114059000,
 1114060500,
 1114061500,
 1114062500,
 1114063500,
 1114064500,
 1114065000,
 1114066500,
 1114067000,
 1114068000,
 1117051000,
 1117052000,
 1117053000,
 1117055500,
 1117056000,
 1117057000,
 1117058000,
 1117059000,
 1117062500,
 1117063000,
 1117064000,
 1117065000,
 1117066000,
 1117068500,
 1117069000,
 1117070000,
 1120052000,
 1120053500,
 1120054000,
 1120055000,
 1120056000,
 1120057000,
 1120058000,
 1120059000,
 1120061500,
 1120062000,
 1120064500,
 1120065000,
 1120066000,
 1120067000,
 1120069000,
 1120072000,
 1120079000,
 1121571000,
 1121573000,
 1121574000,
 1121575000,
 1121576000,
 1121577000,
 1121578000,
 1121581000,
 1121582000,
 1121583000,
 1121584000,
 1121584700,
 1121585000,
 1121586000,
 1121587000,
 1123053600,
 1123054500,
 1123056000,
 1123057000,
 1123060000,
 1123061000,
 1123065000,
 1123066000,
 1123070500,
 1123071000,
 1123072000,
 1123073000,
 1123074000,
 1123075000,
 1126052000,
 1126054000,
 1126055000,
 1126056500,
 1126057000,
 1126057500,
 1126058000,
 1126059000,
 1126060000,
 1126061000,
 1126062000,
 1126063000,
 1126065500,
 1126066000,
 1126068000,
 1126069000,
 1129052500,
 1129055500,
 1129057500,
 1129058000,
 1129059000,
 1129060000,
 1129061000,
 1129062000,
 1129063000,
 1129064000,
 1129065000,
 1129066000,
 1129068500,
 1129070500,
 1129071500,
 1129072500,
 1129076000,
 1129077000,
 1129078000,
 1129081000,
 1130553400,
 1130553500,
 1130554500,
 1130555500,
 1130557500,
 1130559500,
 1130560300,
 1130560800,
 1130561500,
 1130562500,
 1130563500,
 1130564500,
 1130566000,
 1132051100,
 1132051200,
 1132051300,
 1132051400,
 1132051500,
 1132052100,
 1132052200,
 1132066000,
 1132067000,
 1132068000,
 1132068100,
 1132069000,
 1132070000,
 1132071000,
 1135056000,
 1135057000,
 1135058000,
 1135059500,
 1135060000,
 1135061100,
 1135061200,
 1135061900,
 1135062100,
 1135062400,
 1135062500,
 1135063000,
 1135064000,
 1135066500,
 1135067000,
 1135069500,
 1135070000,
 1135071000,
 1135072000,
 1138051000,
 1138052000,
 1138053000,
 1138055100,
 1138055200,
 1138056000,
 1138057000,
 1138058000,
 1138059000,
 1138060000,
 1138062500,
 1138063100,
 1138063200,
 1138064000,
 1138065000,
 1138069000,
 1141052000,
 1141055500,
 1141056500,
 1141058500,
 1141061500,
 1141062000,
 1141064000,
 1141065500,
 1141066000,
 1141068500,
 1141069000,
 1141070000,
 1141071000,
 1141072000,
 1144055500,
 1144056500,
 1144058500,
 1144059000,
 1144060000,
 1144061000,
 1144063000,
 1144065500,
 1144066000,
 1144068000,
 1144069000,
 1144070000,
 1144071000,
 1144072000,
 1144073000,
 1144074000,
 1147051000,
 1147052000,
 1147053000,
 1147054000,
 1147055000,
 1147056000,
 1147057000,
 1147058000,
 1147059000,
 1147060000,
 1147061000,
 1147061100,
 1147062000,
 1147063000,
 1147064000,
 1147065000,
 1147067000,
 1147068000,
 1150051000,
 1150052000,
 1150053000,
 1150053500,
 1150054000,
 1150055000,
 1150056000,
 1150057000,
 1150059000,
 1150059100,
 1150059300,
 1150060300,
 1150060400,
 1150060500,
 1150061100,
 1150061500,
 1150062000,
 1150063000,
 1150064000,
 1150064100,
 1153051000,
 1153052000,
 1153053000,
 1153054000,
 1153055000,
 1153056000,
 1153059500,
 1153072000,
 1153073000,
 1153074000,
 1153075000,
 1153076000,
 1153077000,
 1153078000,
 1153079000,
 1153080000,
 1154551000,
 1154561000,
 1154562000,
 1154563000,
 1154564000,
 1154567000,
 1154568000,
 1154569000,
 1154570000,
 1154571000,
 1156051500,
 1156053500,
 1156054000,
 1156055000,
 1156056000,
 1156058500,
 1156060500,
 1156061000,
 1156062000,
 1156063000,
 1156065000,
 1156066000,
 1156067000,
 1156068000,
 1156069000,
 1156070000,
 1156071000,
 1156072000,
 1159051000,
 1159052000,
 1159053000,
 1159054000,
 1159055000,
 1159056000,
 1159060500,
 1159062000,
 1159063000,
 1159064000,
 1159065000,
 1159065100,
 1159066000,
 1159067000,
 1159068000,
 1162052500,
 1162054500,
 1162056500,
 1162057500,
 1162058500,
 1162059500,
 1162060500,
 1162061500,
 1162062500,
 1162063000,
 1162064500,
 1162065500,
 1162066500,
 1162068500,
 1162069500,
 1162071500,
 1162072500,
 1162073500,
 1162074500,
 1162076500,
 1162077500,
 1165051000,
 1165052000,
 1165053000,
 1165053100,
 1165054000,
 1165055000,
 1165056000,
 1165057000,
 1165058000,
 1165058100,
 1165059000,
 1165060000,
 1165061000,
 1165062000,
 1165062100,
 1165065100,
 1165065200,
 1165066000,
 1168051000,
 1168052100,
 1168053100,
 1168054500,
 1168056500,
 1168058000,
 1168059000,
 1168060000,
 1168061000,
 1168063000,
 1168064000,
 1168065000,
 1168065500,
 1168065600,
 1168066000,
 1168067000,
 1168069000,
 1168070000,
 1168072000,
 1168073000,
 1168074000,
 1168075000,
 1171051000,
 1171052000,
 1171053100,
 1171053200,
 1171054000,
 1171055000,
 1171056100,
 1171056200,
 1171056600,
 1171057000,
 1171058000,
 1171059000,
 1171060000,
 1171061000,
 1171062000,
 1171063100,
 1171063200,
 1171064100,
 1171064200,
 1171064600,
 1171064700,
 1171065000,
 1171067000,
 1171068000,
 1171069000,
 1171071000,
 1171072000,
 1174051500,
 1174052000,
 1174053000,
 1174054000,
 1174055000,
 1174056000,
 1174057000,
 1174058000,
 1174059000,
 1174060000,
 1174061000,
 1174062000,
 1174064000,
 1174065000,
 1174066000,
 1174068500,
 1174069000,
 1174070000]

In [5]:
data_df = pklopen('연령별인구데이터.pkl')
data_df

           시점       행정동코드   행정동명  연령코드  연령단위     총인구수
397    201207  1111051500  청운효자동     0     계  15216.0
398    201208  1111051500  청운효자동     0     계  15234.0
399    201209  1111051500  청운효자동     0     계  15195.0
400    201210  1111051500  청운효자동     0     계  15175.0
401    201211  1111051500  청운효자동     0     계  15160.0
...       ...         ...    ...   ...   ...      ...
79548  202004  1174070000  둔촌제2동   105  100+     13.0
79549  202005  1174070000  둔촌제2동   105  100+     12.0
79550  202006  1174070000  둔촌제2동   105  100+     12.0
79551  202007  1174070000  둔촌제2동   105  100+     12.0
79552  202008  1174070000  둔촌제2동   105  100+     13.0

[899756 rows x 6 columns]

# 각 동별로 초등학생 인구수 변화추이를 맞추는 lstm을 돌리고, 결과를 평균내서 보자.

In [15]:
data_df[data_df.행정동명 == '청운효자동']

         시점       행정동코드   행정동명  연령코드  연령단위     총인구수
397  201207  1111051500  청운효자동     0     계  15216.0
398  201208  1111051500  청운효자동     0     계  15234.0
399  201209  1111051500  청운효자동     0     계  15195.0
400  201210  1111051500  청운효자동     0     계  15175.0
401  201211  1111051500  청운효자동     0     계  15160.0
..      ...         ...    ...   ...   ...      ...
700  202004  1111051500  청운효자동   105  100+     19.0
701  202005  1111051500  청운효자동   105  100+     19.0
702  202006  1111051500  청운효자동   105  100+     19.0
703  202007  1111051500  청운효자동   105  100+     19.0
704  202008  1111051500  청운효자동   105  100+     19.0

[2156 rows x 6 columns]